import {NextRequest,NextResponse} from 'next/server';
import {z} from 'zod';
import {withAuth,rpc,body,ApiError} from '@/lib/server';
const uuid=z.string().uuid();const text=z.string().max(4000);const decimal=z.string().regex(/^-?\d{1,12}(\.\d{1,4})?$/);
const actions:Record<string,{rpc:string;schema:z.ZodTypeAny}>={
 save_personnel:{rpc:'save_personnel',schema:z.object({id:uuid.nullable(),expected_version:z.number().int().nonnegative(),personnel_code:z.union([z.literal(''),z.string().regex(/^\d{7}$/, 'Employee ID must contain seven digits: YYZZSSS.')]),legal_name:z.string().min(1).max(200),display_name:z.string().max(200),engagement:z.enum(['employee','contractor','freelancer','other']),department_id:uuid,position:z.string().min(1).max(200),email:z.string().email(),phone:z.string().max(80),start_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),status:z.enum(['active','inactive','suspended','departed']),currency:z.string().length(3),default_rate:decimal,payment_structure:z.enum(['fixed','hourly','per_task','project','custom']),notes:text,payment_info:z.string().max(4000).optional()})},
 save_record:{rpc:'save_record',schema:z.object({id:uuid.nullable(),request_id:uuid,expected_version:z.number().int().nonnegative(),personnel_id:uuid,period:z.string().regex(/^\d{4}-\d{2}-01$/),notes:text,items:z.array(z.object({title:z.string().min(1).max(200),description:text,project_id:uuid.nullable(),completed_on:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),calculation:z.enum(['fixed','quantity','hours']),quantity:decimal,rate:decimal,fixed_amount:decimal,notes:text})).min(1).max(100),adjustments:z.array(z.object({kind:z.enum(['bonus','reimbursement','allowance','commission','deduction','correction','other']),description:z.string().min(1).max(500),amount:decimal,notes:text})).max(100)})},
 transition:{rpc:'transition_record',schema:z.object({id:uuid,expected_version:z.number().int(),status:z.enum(['submitted','approved','awaiting_payment','archived','draft']),reason:z.string().max(1000)})},
 payment:{rpc:'record_payment',schema:z.object({record_id:uuid,request_id:uuid,payment_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount:decimal,method:z.enum(['bank_transfer','cash','card','wallet','other']),reference:z.string().min(1).max(200),paying_account:z.string().max(200),notes:text})},
 reverse_payment:{rpc:'reverse_payment',schema:z.object({id:uuid,reason:z.string().min(10).max(1000)})},
 directory:{rpc:'save_directory',schema:z.object({kind:z.enum(['department','project']),id:uuid.nullable(),name:z.string().min(1).max(150),code:z.string().regex(/^[A-Z]{2}$/).optional(),status:z.enum(['active','archived'])})},
 profile:{rpc:'save_profile',schema:z.object({id:uuid,full_name:z.string().min(1).max(200),role:z.enum(['super_admin','finance','manager','viewer','employee']),active:z.boolean()})},
};
export async function POST(req:NextRequest){return withAuth(req,async db=>{const raw=await body(req);const action=actions[raw.action];if(!action)throw new ApiError(400,'Unknown action.');const input=action.schema.parse(raw.input);return NextResponse.json(await rpc(db,action.rpc,{input}));});}
