import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
await fs.mkdir('work/route-tests',{recursive:true});
async function compile(input,output,replacements=[]){let source=await fs.readFile(input,'utf8');for(const [a,b] of replacements)source=source.replaceAll(a,b);const result=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}});await fs.writeFile('work/route-tests/'+output,result.outputText);}
for(const name of ['workspace-auth','proof','presentation'])await compile('lib/'+name+'.ts',name+'.mjs');
await compile('lib/server.ts','server.mjs',[["'next/server'","'next/server.js'"],["'./workspace-auth'","'./workspace-auth.mjs'"]]);
await compile('app/api/proofs/[id]/route.ts','route.mjs',[["'next/server'","'next/server.js'"],["'@/lib/server'","'./stub.mjs'"],["'@/lib/proof'","'./proof.mjs'"]]);
await fs.writeFile('work/route-tests/stub.mjs',`import {ApiError,readLimited} from './server.mjs';export {ApiError,readLimited};export let state={};export const reset=s=>state=s;export const finance=p=>{if(p.role!=='finance')throw new ApiError(403,'Finance access required');};export async function withAuth(req,fn){try{return await fn({from:(table)=>{const query={select:()=>query,eq:()=>query,single:async()=>({data:table==='documents'?state.document:state.payment})};return query;},storage:{from:(bucket)=>({createSignedUrl:async(path,expires,options)=>{state.signed={bucket,path,expires,options};return state.signError?{error:{message:'failure'}}:{data:{signedUrl:'https://fixture.supabase.co/storage/v1/object/sign/private/file?token=fixture'}};},upload:async(path,bytes,options)=>{state.uploads++;state.bytes=bytes;state.path=path;state.mime=options.contentType;return {error:state.uploadError||null};}})}},null,{role:state.role||'finance'});}catch(e){return Response.json({error:e.message},{status:e.status||500});}}export async function rpc(db,name,{input}){if(state.attachError)throw new ApiError(502,'Attachment interrupted');state.payment.proof_path=input.path;state.attachments++;}`);
const auth=await import('../work/route-tests/workspace-auth.mjs');const proof=await import('../work/route-tests/proof.mjs');const {POST}=await import('../work/route-tests/route.mjs');const stub=await import('../work/route-tests/stub.mjs');
const companyUser={email:'person@aerinyustudios.com',email_confirmed_at:'2026-01-01',identities:[{provider:'google',identity_data:{email:'person@aerinyustudios.com',email_verified:true,custom_claims:{hd:'aerinyustudios.com'}}}]};
test('only verified company Google identities are accepted; metadata cannot grant access',()=>{
 assert.equal(auth.isWorkspaceIdentity(companyUser),true);
 for(const user of [{...companyUser,email:'person@aerinyustudios.com.evil.test'},{...companyUser,identities:[]},{...companyUser,email_confirmed_at:null},{...companyUser,identities:[{provider:'email',identity_data:companyUser.identities[0].identity_data}]},{...companyUser,identities:[{provider:'google',identity_data:{...companyUser.identities[0].identity_data,custom_claims:{hd:'other.test'}}}]},{email:companyUser.email,email_confirmed_at:'yes',user_metadata:{custom_claims:{hd:'aerinyustudios.com'}},identities:[]}])assert.equal(auth.isWorkspaceIdentity(user),false);
 const token=amr=>'x.'+Buffer.from(JSON.stringify({amr})).toString('base64url')+'.x';assert.equal(auth.hasOAuthAuthentication(token([{method:'oauth'}])),true);assert.equal(auth.hasOAuthAuthentication(token([{method:'password'}])),false);
});
const id='00000000-0000-4000-8000-000000000001',params={params:Promise.resolve({id})};
function reset(extra={}){stub.reset({payment:{id,proof_path:null},uploads:0,attachments:0,...extra});}
const pdf=new TextEncoder().encode('%PDF-1.7\nFixture document');
function request(bytes=pdf){return new Request('http://localhost/api/proofs/'+id,{method:'POST',body:bytes,headers:{'Content-Type':'application/octet-stream'}});}
test('binary proof upload preserves bytes; retry does not upload or attach twice',async()=>{reset();assert.equal((await POST(request(),params)).status,200);assert.deepEqual(stub.state.bytes,pdf);assert.equal(stub.state.mime,'application/pdf');assert.equal((await POST(request(),params)).status,200);assert.equal(stub.state.uploads,1);assert.equal(stub.state.attachments,1);});
test('proof retry recovers an uploaded file after interrupted finalization',async()=>{reset({attachError:true});assert.equal((await POST(request(),params)).status,502);const previous=stub.state.path;stub.state.attachError=false;stub.state.uploadError={statusCode:'409'};assert.equal((await POST(request(),params)).status,200);assert.equal(stub.state.path,previous);assert.equal(stub.state.attachments,1);});
test('proof upload rejects unsupported, empty, oversized and unauthorized uploads',async()=>{reset();assert.equal((await POST(request(new Uint8Array()),params)).status,400);assert.equal((await POST(request(new TextEncoder().encode('<script>')),params)).status,400);assert.equal((await POST(request(new Uint8Array(proof.MAX_PROOF_BYTES+1)),params)).status,413);assert.equal(stub.state.uploads,0);reset({role:'viewer'});assert.equal((await POST(request(),params)).status,403);});
test('multipart uploads remain compatible and client validates before recording payment',async()=>{reset();const form=new FormData();form.append('file',new File([pdf],'test.pdf',{type:'application/pdf'}));assert.equal((await POST(new Request('http://localhost/api/proofs/'+id,{method:'POST',body:form}),params)).status,200);await assert.rejects(()=>proof.validateProof(new File(['text'],'false.pdf',{type:'application/pdf'})),/Choose/);await assert.rejects(()=>proof.validateProof(new File([new Uint8Array(proof.MAX_PROOF_BYTES+1)],'large.pdf')),/4 MB/);});
await compile('lib/google-oauth.ts','google-oauth.mjs',[["'next/server'","'next/server.js'"],["'./server'","'./server.mjs'"]]);
await compile('app/api/auth/google/route.ts','google-start.mjs',[["'next/server'","'next/server.js'"],["'@/lib/server'","'./server.mjs'"],["'@/lib/google-oauth'","'./google-oauth.mjs'"],["'@/lib/workspace-auth'","'./workspace-auth.mjs'"]]);
test('Google sign-in uses PKCE, an HttpOnly verifier and exact callback; rejects cross-origin start',async()=>{
 const savedUrl=process.env.SUPABASE_URL,savedKey=process.env.SUPABASE_ANON_KEY;
 process.env.SUPABASE_URL='https://fixture.supabase.co';process.env.SUPABASE_ANON_KEY='fixture-key';
 try{const {NextRequest}=await import('next/server.js');const route=await import('../work/route-tests/google-start.mjs');
  const res=await route.POST(new NextRequest('https://studio.example/api/auth/google',{method:'POST',headers:{origin:'https://studio.example'}}));assert.equal(res.status,200);const {url}=await res.json();const target=new URL(url);assert.equal(target.searchParams.get('provider'),'google');assert.equal(target.searchParams.get('redirect_to'),'https://studio.example/api/auth/google/callback');assert.equal(target.searchParams.get('hd'),'aerinyustudios.com');assert.ok(target.searchParams.get('code_challenge'));assert.match(res.headers.get('set-cookie'),/HttpOnly/i);assert.match(res.headers.get('set-cookie'),/SameSite=lax/i);assert.match(res.headers.get('set-cookie'),/Secure/i);
  assert.equal((await route.POST(new NextRequest('https://studio.example/api/auth/google',{method:'POST',headers:{origin:'https://evil.example'}}))).status,403);
 }finally{if(savedUrl===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=savedUrl;if(savedKey===undefined)delete process.env.SUPABASE_ANON_KEY;else process.env.SUPABASE_ANON_KEY=savedKey;}
});

await compile('app/api/documents/[id]/route.ts','document-route.mjs',[["'next/server'","'next/server.js'"],["'@/lib/server'","'./stub.mjs'"]]);
test('Vercel downloads use short-lived private URLs after finance authorization',async()=>{
 const {GET:proofGet}=await import('../work/route-tests/route.mjs');const {GET:documentGet}=await import('../work/route-tests/document-route.mjs');
 reset({payment:{id,proof_path:'proofs/'+id+'/file.pdf'}});let response=await proofGet(new Request('https://studio.example/api/proofs/'+id),params);assert.equal(response.status,303);assert.equal(stub.state.signed.expires,60);assert.equal(stub.state.signed.options.download,'payment-proof.pdf');assert.equal(stub.state.signed.bucket,'payment-proofs');assert.ok(response.headers.get('location').startsWith('https://fixture.supabase.co/'));
 reset({document:{storage_path:'personnel/fixture/receipt.pdf',document_number:'ASGD-260916-001'}});response=await documentGet(new Request('https://studio.example/api/documents/'+id),params);assert.equal(response.status,303);assert.equal(stub.state.signed.options.download,'ASGD-260916-001.pdf');assert.equal(stub.state.signed.bucket,'financial-documents');
 reset({role:'viewer',payment:{id,proof_path:'proofs/file.pdf'}});assert.equal((await proofGet(new Request('https://studio.example/api/proofs/'+id),params)).status,403);assert.equal(stub.state.signed,undefined);
 reset({payment:{id,proof_path:null}});assert.equal((await proofGet(new Request('https://studio.example/api/proofs/'+id),params)).status,404);
 reset({signError:true,payment:{id,proof_path:'proofs/file.pdf'}});assert.equal((await proofGet(new Request('https://studio.example/api/proofs/'+id),params)).status,502);
});
