import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const ids={admin:'00000000-0000-4000-8000-000000000001',finance:'00000000-0000-4000-8000-000000000002',manager:'00000000-0000-4000-8000-000000000003',viewer:'00000000-0000-4000-8000-000000000004'};
async function actor(role='finance'){await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({amr:[{method:'oauth'}]})]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[role]||'']);await db.exec('set role '+(role==='anon'?'anon':'authenticated'));}
async function rpc(name,input){const r=await db.query(`select public.${name}(${input===undefined?'':'$1::jsonb'}) as result`,input===undefined?[]:[JSON.stringify(input)]);return r.rows[0].result;}
let person,record,department;
const item={title:'Production work',description:'Reviewed delivery',project_id:null,completed_on:'2026-08-17',calculation:'hours',quantity:'3.3333',rate:'10.1250',fixed_amount:'0',notes:''};
before(async()=>{await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create table auth.identities(user_id uuid,provider text,identity_data jsonb);create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert on storage.objects to authenticated;`);for(const migration of ['202609160001_operations.sql','202609160002_reports.sql','202609160003_payment_details.sql','202609160004_employee_receipt_ids.sql','202609160005_google_workspace_access.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+migration,import.meta.url),'utf8'));for(const [role,id] of Object.entries(ids)){await db.query('insert into auth.users values($1,$2,now())',[id,role+'@aerinyustudios.com']);await db.query('insert into auth.identities values($1,$2,$3)',[id,'google',JSON.stringify({email:role+'@aerinyustudios.com',email_verified:true,custom_claims:{hd:'aerinyustudios.com'}})]);await db.query('insert into public.profiles(id,full_name,role) values($1,$2,$3)',[id,role,role==='admin'?'super_admin':role]);}await actor();});
after(()=>db.close());
test('unauthenticated RPCs and direct writes are denied',async()=>{await actor('anon');await assert.rejects(()=>rpc('workspace_data'),/permission denied/i);await actor();await assert.rejects(()=>db.exec("insert into public.departments(name) values('Forbidden')"),/permission denied/i);});
test('finance can create directories and personnel with manually assigned employee IDs',async()=>{await actor();department=(await rpc('save_directory',{kind:'department',id:null,name:'Engineering',code:'GD',status:'active'})).id;person=(await rpc('save_personnel',{id:null,expected_version:0,personnel_code:'2600001',legal_name:'John Example',display_name:'John',engagement:'contractor',department_id:department,position:'Senior Developer',email:'john@example.test',phone:'',start_date:'2026-01-01',status:'active',currency:'MYR',default_rate:'10.125',payment_structure:'hourly',notes:'',payment_info:'private bank details'})).id;const w=await rpc('workspace_data');assert.equal(w.personnel[0].personnel_code,'2600001');assert.equal(w.personnel[0].default_rate,'10.1250');assert.ok(!JSON.stringify(w.personnel).includes('private bank'));});
let draftInput;
test('decimal calculations round each line; adjustments and idempotency are exact',async()=>{await actor('manager');draftInput={id:null,request_id:crypto.randomUUID(),expected_version:0,personnel_id:person,period:'2026-08-01',notes:'August work',items:[item],adjustments:[{kind:'bonus',description:'Delivery bonus',amount:'2.20',notes:''},{kind:'deduction',description:'Correction deduction',amount:'0.11',notes:''}]};record=(await rpc('save_record',draftInput)).id;assert.equal((await rpc('save_record',draftInput)).id,record);const result=(await db.query('select public.record_detail($1) as result',[record])).rows[0].result;assert.equal(result.record.work_subtotal,'33.75');assert.equal(Number(result.record.total),35.84);assert.equal(result.items[0].quantity,'3.3333');});
test('viewer mutations, manager approvals and payment-data access are denied',async()=>{await actor('viewer');await assert.rejects(()=>rpc('save_record',draftInput),/Permission denied/);await actor('manager');await assert.rejects(()=>rpc('transition_record',{id:record,expected_version:1,status:'approved',reason:''}),/not allowed/);assert.equal((await db.query('select * from public.personnel_payment_details')).rows.length,0);assert.deepEqual((await rpc('workspace_data')).payments,[]);});
test('workflow requires submission and approval, freezes amounts, snapshots identity',async()=>{await actor('manager');await rpc('transition_record',{id:record,expected_version:1,status:'submitted',reason:''});await assert.rejects(()=>rpc('transition_record',{id:record,expected_version:2,status:'approved',reason:''}),/Permission denied/);await actor();await rpc('transition_record',{id:record,expected_version:2,status:'approved',reason:''});await assert.rejects(()=>rpc('save_record',{...draftInput,id:record,expected_version:3}),/Only draft/);const d=(await db.query('select public.record_detail($1) as result',[record])).rows[0].result;assert.equal(d.record.snapshot.position,'Senior Developer');const w=await rpc('workspace_data');await rpc('save_personnel',{...w.personnel[0],expected_version:1,position:'Director'});const updated=(await db.query('select public.record_detail($1) as result',[record])).rows[0].result;assert.equal(updated.record.snapshot.position,'Senior Developer');});
let payment;
test('partial payments keep an exact remaining balance; retries do not double-pay',async()=>{await actor();const input={record_id:record,request_id:crypto.randomUUID(),payment_date:'2026-08-31',amount:'10.01',method:'bank_transfer',reference:'TX-001',paying_account:'Operating',notes:''};payment=(await rpc('record_payment',input)).id;assert.equal((await rpc('record_payment',input)).id,payment);assert.equal((await rpc('workspace_data')).payments.find(p=>p.id===payment).receipt_number,'ASGD-260831-001');const r=(await rpc('workspace_data')).records[0];assert.equal(r.status,'awaiting_payment');assert.equal(Number(r.balance),25.83);await assert.rejects(()=>rpc('record_payment',{...input,request_id:crypto.randomUUID(),amount:'25.84'}),/within the remaining balance/);await assert.rejects(()=>rpc('transition_record',{id:record,expected_version:r.version,status:'draft',reason:'Need to correct tasks'}),/Reverse existing payments/);});
test('receipts are snapshots; storage is private and issued versions cannot be changed',async()=>{await actor();const d=await rpc('reserve_document',{record_id:record,kind:'receipt',payment_id:payment});assert.equal(Number(d.snapshot.payment.remaining_balance),25.83);await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['financial-documents',d.storage_path]);await rpc('finalize_document',{id:d.id,sha256:'a'.repeat(64),bytes:100});await assert.rejects(()=>db.query("update public.documents set snapshot='{}' where id=$1",[d.id]),/permission denied/);await actor('manager');assert.equal((await db.query('select * from storage.objects')).rows.length,0);await actor();});
test('exact full payment marks paid; overpayment rejected; reversal restores balance and audit',async()=>{await actor();const p=await rpc('record_payment',{record_id:record,request_id:crypto.randomUUID(),payment_date:'2026-08-31',amount:'25.83',method:'bank_transfer',reference:'TX-002',paying_account:'',notes:''});let w=await rpc('workspace_data');assert.equal(w.records[0].status,'paid');assert.equal(Number(w.records[0].balance),0);await assert.rejects(()=>rpc('record_payment',{record_id:record,request_id:crypto.randomUUID(),payment_date:'2026-08-31',amount:'1',method:'cash',reference:'bad',paying_account:'',notes:''}),/Only approved/);await rpc('reverse_payment',{id:p.id,reason:'Duplicate transaction entered in error'});w=await rpc('workspace_data');assert.equal(w.records[0].status,'awaiting_payment');assert.equal(Number(w.records[0].balance),25.83);assert.ok(w.activity.some(a=>a.action==='Payment reversed'));});
test('stale edits and invalid dates fail atomically; no unauthorized role escalation',async()=>{await actor();await assert.rejects(async()=>rpc('save_personnel',{...(await rpc('workspace_data')).personnel[0],expected_version:1}),/Reload/);await actor('manager');await assert.rejects(()=>rpc('save_profile',{id:ids.manager,role:'super_admin',full_name:'Escalation',active:true}),/Permission denied/);await actor('admin');await assert.rejects(()=>rpc('save_profile',{id:ids.admin,role:'viewer',full_name:'Admin',active:true}),/own administrative/);await actor();await assert.rejects(()=>rpc('save_record',{...draftInput,request_id:crypto.randomUUID(),period:'2026-09-01'}),/Completion dates/);assert.equal((await rpc('workspace_data')).records.length,1);});
test('payment information reveal is restricted and audited',async()=>{await actor('manager');await assert.rejects(()=>db.query('select public.read_payment_details($1)',[person]),/Permission denied/);await actor();const result=(await db.query('select public.read_payment_details($1) as result',[person])).rows[0].result;assert.equal(result.payment_info,'private bank details');assert.ok((await rpc('workspace_data')).activity.some(a=>a.action==='Personnel payment details viewed'));});
test('project expenditure uses line amounts and excludes record adjustments',async()=>{await actor();const report=await rpc('project_report',{from:'2026-08-01',to:'2026-08-01'});assert.equal(report.rows[0].amount,'33.75');assert.equal(report.rows[0].label,'Unassigned');await actor('viewer');await assert.rejects(()=>rpc('project_report',{from:'2026-08-01',to:'2026-08-01'}),/Permission denied/);});
test('zero-payable records can be settled without inventing a payment',async()=>{await actor();const id=(await rpc('save_record',{...draftInput,request_id:crypto.randomUUID(),period:'2026-07-01',items:[{...item,completed_on:'2026-07-02',calculation:'fixed',fixed_amount:'0'}],adjustments:[]})).id;await rpc('transition_record',{id,expected_version:1,status:'submitted',reason:''});await rpc('transition_record',{id,expected_version:2,status:'approved',reason:''});await rpc('transition_record',{id,expected_version:3,status:'awaiting_payment',reason:''});const w=await rpc('workspace_data');assert.equal(w.records.find(r=>r.id===id).status,'paid');assert.equal(w.payments.filter(p=>p.record_id===id).length,0);});


test('employee IDs reject invalid formats, wrong hire year and duplicates',async()=>{
 await actor();const p=(await rpc('workspace_data')).personnel[0];
 for(const code of ['25001001','26AB001','2500001'])await assert.rejects(()=>rpc('save_personnel',{...p,expected_version:p.version,personnel_code:code}),/seven digits|year of hire/);
 await assert.rejects(()=>rpc('save_personnel',{...p,id:null,expected_version:0}),/unique constraint/);
 await rpc('save_personnel',{...p,expected_version:p.version,personnel_code:'2699001'});
 const r=(await db.query('select public.record_detail($1) as result',[record])).rows[0].result;
 assert.equal(r.record.snapshot.personnel_code,'2600001');assert.equal((await rpc('workspace_data')).personnel[0].personnel_code,'2699001');
 const leading=(await rpc('save_personnel',{...p,id:null,personnel_code:'0500001',start_date:'2005-01-01',expected_version:0})).id;
 assert.equal((await rpc('workspace_data')).personnel.find(p=>p.id===leading).personnel_code,'0500001');
});
test('receipt sequences advance per department and payment day without truncating',async()=>{
 await db.exec('reset role');
 const a=(await db.query('select private.next_receipt_number($1,$2) as n',[record,'2026-08-30'])).rows[0].n;
 const b=(await db.query('select private.next_receipt_number($1,$2) as n',[record,'2026-08-30'])).rows[0].n;
 assert.equal(a,'ASGD-260830-001');assert.equal(b,'ASGD-260830-002');
 await db.exec("update private.receipt_counters set last_number=999 where payment_date='2026-08-30'");
 assert.equal((await db.query('select private.next_receipt_number($1,$2) as n',[record,'2026-08-30'])).rows[0].n,'ASGD-260830-1000');
 await actor();await assert.rejects(()=>rpc('save_directory',{kind:'department',id:null,name:'Other',code:'GD',status:'active'}),/unique constraint/);
});
test('Google Workspace restrictions also protect direct RPC and table access',async()=>{
 await actor();await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({amr:[{method:'password'}]})]);await assert.rejects(()=>rpc('workspace_data'),/Permission denied/);assert.equal((await db.query('select * from public.personnel')).rows.length,0);
 await actor();await db.exec('reset role');await db.query("update auth.identities set identity_data=jsonb_set(identity_data,'{custom_claims,hd}',$2::jsonb) where user_id=$1",[ids.finance,JSON.stringify('other.example')]);await actor();await assert.rejects(()=>rpc('workspace_data'),/Permission denied/);
 await db.exec('reset role');await db.query("update auth.identities set identity_data=jsonb_set(identity_data,'{custom_claims,hd}',$2::jsonb) where user_id=$1",[ids.finance,JSON.stringify('aerinyustudios.com')]);await actor();assert.ok((await rpc('workspace_data')).profile);
});
