'use client';
import {useState,useRef,FormEvent} from 'react';
import {Plus,Trash2,ArrowLeft,ShieldCheck} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Field,Choice,Modal,Busy,action,api} from './controls';
import {currencies,money,lineTotal,total} from '@/lib/money';
import {label,decimalLabel} from '@/lib/presentation';
import {uploadProof} from './proof-upload';
import {validateProof} from '@/lib/proof';
import type {Person,WorkspaceData,WorkItem,Adjustment,RecordDetail,RecordRow} from '@/lib/types';
export function PersonnelForm({person,data,onClose,onSaved}:{person?:Person;data:WorkspaceData;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [v,setV]=useState({id:person?.id||null,expected_version:person?.version||0,personnel_code:person?.personnel_code||'',legal_name:person?.legal_name||'',display_name:person?.display_name||'',engagement:person?.engagement||'contractor',department_id:person?.department_id||data.departments[0]?.id||'',position:person?.position||'',email:person?.email||'',phone:person?.phone||'',start_date:person?.start_date||new Date().toISOString().slice(0,10),status:person?.status||'active',currency:person?.currency||'MYR',default_rate:decimalLabel(person?.default_rate||'0'),payment_structure:person?.payment_structure||'fixed',notes:person?.notes||''});
 const [paymentInfo,setPaymentInfo]=useState<string|undefined>();const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const set=(key:string,value:string)=>setV(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await action('save_personnel',{...v,...(paymentInfo!==undefined?{payment_info:paymentInfo}:{})});await onSaved();onClose();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal large title={person?'Edit personnel':'Add personnel'} description={person?person.personnel_code:'New employee IDs are assigned automatically. Use the People hub to also create a company account.'} onClose={()=>!busy&&onClose()}><form onSubmit={submit}><div className="form-grid">
 <Field label="Employee ID"><input required={!!person} disabled={!person} inputMode="numeric" pattern="[0-9]{7}" minLength={7} maxLength={7} placeholder={person?"YYZZSSS":"Assigned automatically"} title="Seven digits: year of hire, two-digit assigned number, three-digit sequence." value={v.personnel_code} onChange={e=>set('personnel_code',e.target.value)}/><small>YY: year of hire. ZZ: assigned number. SSS: sequence.</small></Field><Field label="Full legal name"><input required maxLength={200} value={v.legal_name} onChange={e=>set('legal_name',e.target.value)}/></Field><Field label="Display name"><input value={v.display_name} onChange={e=>set('display_name',e.target.value)}/></Field>
 <Field label="Engagement type"><Choice value={v.engagement} onChange={x=>set('engagement',x)} options={['employee','contractor','freelancer','other']}/></Field><Field label="Department"><Choice value={v.department_id} onChange={x=>set('department_id',x)} options={data.departments.map(d=>({value:d.id,label:d.name}))}/></Field>
 <Field label="Position"><input required value={v.position} onChange={e=>set('position',e.target.value)}/></Field><Field label="Status"><Choice value={v.status} onChange={x=>set('status',x)} options={['active','inactive','suspended','departed']}/></Field>
 <Field label="Email"><input required type="email" value={v.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Phone"><input value={v.phone} onChange={e=>set('phone',e.target.value)}/></Field>
 <Field label="Hire date"><input required type="date" value={v.start_date} onChange={e=>set('start_date',e.target.value)}/></Field><Field label="Payment currency"><Choice value={v.currency} onChange={x=>set('currency',x)} options={[...currencies]}/></Field>
 <Field label="Payment structure"><Choice value={v.payment_structure} onChange={x=>set('payment_structure',x)} options={['fixed','hourly','per_task','project','custom']}/></Field><Field label="Default rate"><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={v.default_rate} onChange={e=>set('default_rate',e.target.value)}/></Field>
 <Field label="Internal notes" wide><textarea rows={3} value={v.notes} onChange={e=>set('notes',e.target.value)}/></Field>
 <Field label={person?'Replace payment information (leave untouched to retain existing details)':'Payment information (optional / finance access only)'} wide><textarea rows={2} value={paymentInfo??''} onChange={e=>setPaymentInfo(e.target.value)}/></Field></div>
 {!data.departments.length&&<p className="error">Create a department in Administration before adding personnel.</p>}{error&&<p role="alert" className="error">{error}</p>}<div className="form-footer"><button className="secondary" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!v.department_id}>{busy?<Busy/>:'Save personnel'}</button></div></form></Modal>
}
export function RecordEditor({data,detail,onClose,onSaved}:{data:WorkspaceData;detail?:RecordDetail;onClose:()=>void;onSaved:(id:string)=>Promise<void>}){
 const [personId,setPersonId]=useState(detail?.record.personnel_id||'');const [month,setMonth]=useState(detail?.record.period.slice(0,7)||new Date().toISOString().slice(0,7));const person=data.personnel.find(p=>p.id===personId);const currency=detail?.record.currency||person?.currency||'MYR';
 const blank=():WorkItem=>({title:'',description:'',project_id:'',completed_on:month+'-01',calculation:person?.payment_structure==='hourly'?'hours':'fixed',quantity:'1',rate:person?.default_rate||'0',fixed_amount:'0',notes:''});
 const [items,setItems]=useState<WorkItem[]>(detail?.items.map(i=>({...i,project_id:i.project_id||''}))||[blank()]);const [adjustments,setAdjustments]=useState<Adjustment[]>(detail?.adjustments||[]);const [notes,setNotes]=useState(detail?.record.notes||'');const [busy,setBusy]=useState(false),[error,setError]=useState('');const requestId=useRef(crypto.randomUUID());
 const updateItem=(index:number,key:string,value:string)=>setItems(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));
 const updateAdjustment=(index:number,key:string,value:string)=>setAdjustments(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));
 const safeTotal=()=>{try{return money(total(items,adjustments,currency),currency)}catch{return 'Enter valid amounts'}};
 const labels=data.personnel.filter(p=>p.status==='active'||p.id===personId).map(p=>({id:p.id,label:p.personnel_code+' / '+p.legal_name}));
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await action('save_record',{id:detail?.record.id||null,request_id:requestId.current,expected_version:detail?.record.version||0,personnel_id:personId,period:month+'-01',notes,items:items.map(i=>({...i,project_id:i.project_id||null})),adjustments});await onSaved(result.id);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={save} className="record-editor"><button className="text-button back" type="button" onClick={onClose}><ArrowLeft size={16}/> Back to work records</button><div className="page-heading"><div><p className="eyebrow">WORK RECORDS</p><h1>{detail?'Edit monthly record':'New monthly record'}</h1><p className="muted">Personnel details are filled from the central directory.</p></div><span className="status status-draft">Draft</span></div><section className="panel form-section"><h2>01 / Personnel & reporting period</h2><div className="form-grid"><Field label="Employee ID or name"><Combobox items={labels} itemToStringLabel={item=>item.label} value={labels.find(l=>l.id===personId)||null} onValueChange={v=>{setPersonId(v?.id||'');const selected=data.personnel.find(p=>p.id===v?.id);if(selected)setItems(rows=>rows.map(row=>!row.title?{...row,rate:selected.default_rate,calculation:selected.payment_structure==='hourly'?'hours':'fixed',fixed_amount:selected.payment_structure==='fixed'?selected.default_rate:'0'}:row))}} disabled={!!detail}><ComboboxInput placeholder="Search employee ID or name"/><ComboboxContent><ComboboxEmpty>No active personnel found.</ComboboxEmpty><ComboboxList>{item=><ComboboxItem key={item.id} value={item}>{item.label}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></Field><Field label="Reporting month"><input type="month" required value={month} disabled={!!detail} onChange={e=>setMonth(e.target.value)}/></Field></div>{person&&<div className="person-strip"><strong>{person.legal_name}</strong><span>{person.position}</span><span>{person.department}</span><span>{label(person.engagement)}</span><b>{currency}</b></div>}</section>
 <section className="panel form-section"><div className="section-line"><h2>02 / Work & deliverables</h2><span className="muted">{items.length} line items</span></div>{items.map((item,i)=><div className="work-item" key={i}><div className="item-heading"><span>ITEM {String(i+1).padStart(2,'0')}</span><button type="button" className="icon-button" aria-label={'Remove work item '+(i+1)} disabled={items.length===1} onClick={()=>setItems(items.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div><div className="form-grid"><Field label="Task / deliverable"><input required value={item.title} onChange={e=>updateItem(i,'title',e.target.value)}/></Field><Field label="Project"><Choice value={item.project_id||'none'} onChange={v=>updateItem(i,'project_id',v==='none'?'':v)} options={[{value:'none',label:'No project'},...data.projects.map(p=>({value:p.id,label:p.name}))]}/></Field><Field label="Description" wide><textarea value={item.description} rows={2} onChange={e=>updateItem(i,'description',e.target.value)}/></Field></div><div className="item-calculation"><Field label="Completion date"><input required type="date" value={item.completed_on} onChange={e=>updateItem(i,'completed_on',e.target.value)}/></Field><Field label="Calculation"><Choice value={item.calculation} onChange={v=>updateItem(i,'calculation',v)} options={[{value:'fixed',label:'Fixed amount'},{value:'quantity',label:'Quantity × rate'},{value:'hours',label:'Hours × rate'}]}/></Field>{item.calculation==='fixed'?<Field label="Fixed amount"><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={item.fixed_amount} onChange={e=>updateItem(i,'fixed_amount',e.target.value)}/></Field>:<><Field label={item.calculation==='hours'?'Hours':'Quantity'}><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={item.quantity} onChange={e=>updateItem(i,'quantity',e.target.value)}/></Field><Field label="Rate"><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={item.rate} onChange={e=>updateItem(i,'rate',e.target.value)}/></Field></>}<div className="line-amount"><span>Line total</span><strong>{(()=>{try{return money(lineTotal(item,currency),currency)}catch{return 'Invalid amount'}})()}</strong></div></div><Field label="Item notes (optional)"><input value={item.notes} onChange={e=>updateItem(i,'notes',e.target.value)}/></Field></div>)}<button type="button" className="secondary" disabled={items.length>=100} onClick={()=>setItems([...items,blank()])}><Plus size={16}/> Add work item</button></section>
 <section className="panel form-section"><h2>03 / Adjustments</h2>{adjustments.map((a,i)=><div className="adjustment-row" key={i}><Field label="Type"><Choice value={a.kind} onChange={v=>updateAdjustment(i,'kind',v)} options={['bonus','reimbursement','allowance','commission','deduction','correction','other']}/></Field><Field label="Description"><input required value={a.description} onChange={e=>updateAdjustment(i,'description',e.target.value)}/></Field><Field label="Amount"><input required inputMode="decimal" pattern="-?[0-9]+(\.[0-9]{1,4})?" value={a.amount} onChange={e=>updateAdjustment(i,'amount',e.target.value)}/></Field><Field label="Notes"><input value={a.notes} onChange={e=>updateAdjustment(i,'notes',e.target.value)}/></Field><button type="button" className="icon-button" aria-label={'Remove adjustment '+(i+1)} onClick={()=>setAdjustments(adjustments.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div>)}<p className="muted help-text">Enter deductions as positive amounts. Corrections may be positive or negative.</p><button type="button" className="secondary" disabled={adjustments.length>=100} onClick={()=>setAdjustments([...adjustments,{kind:'bonus',description:'',amount:'0',notes:''}])}><Plus size={16}/> Add adjustment</button></section>
 <section className="panel form-section"><Field label="Statement notes"><textarea value={notes} rows={3} onChange={e=>setNotes(e.target.value)}/></Field><div className="total-strip"><span>TOTAL PAYABLE</span><strong>{safeTotal()}</strong></div><p className="muted"><ShieldCheck size={14} className="inline-icon"/> Final amounts are recalculated and validated when saved.</p></section>{error&&<p role="alert" className="error">{error}</p>}<div className="form-footer"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!personId}>{busy?<Busy/>:'Save draft & review'}</button></div></form>
}
export function PaymentForm({record,onClose,onSaved}:{record:RecordRow;onClose:()=>void;onSaved:()=>Promise<void>}){const [v,setV]=useState({record_id:record.id,request_id:crypto.randomUUID(),payment_date:new Date().toISOString().slice(0,10),amount:record.balance,method:'bank_transfer',reference:'',paying_account:'',notes:''});const [recordedId,setRecordedId]=useState<string|null>(null);const [proof,setProof]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,x:string)=>setV(v=>({...v,[k]:x}));async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');let paymentId=recordedId;try{if(proof)await validateProof(proof);if(!paymentId){const result=await action('payment',v);paymentId=result.id;setRecordedId(paymentId);}if(proof)await uploadProof(paymentId!,proof);await onSaved();onClose();}catch(e){setError((paymentId?'Payment saved. Attachment not completed. ':'')+(e as Error).message);}finally{setBusy(false)}}return <Modal title="Record payment" description={record.statement_number+' / Balance '+money(record.balance,record.currency)} onClose={()=>!busy&&onClose()}><form onSubmit={save}><fieldset className="form-grid" disabled={busy||!!recordedId}><Field label="Payment date"><input type="date" required value={v.payment_date} onChange={e=>set('payment_date',e.target.value)}/></Field><Field label={'Amount paid ('+record.currency+')'}><input inputMode="decimal" required value={v.amount} pattern="[0-9]+(\.[0-9]{1,2})?" onChange={e=>set('amount',e.target.value)}/></Field><Field label="Method"><Choice value={v.method} onChange={x=>set('method',x)} options={['bank_transfer','cash','card','wallet','other']}/></Field><Field label="Transaction reference"><input required value={v.reference} onChange={e=>set('reference',e.target.value)}/></Field><Field label="Paying account (optional)" wide><input value={v.paying_account} onChange={e=>set('paying_account',e.target.value)}/></Field><Field label="Internal note" wide><textarea value={v.notes} onChange={e=>set('notes',e.target.value)}/></Field></fieldset><Field label="Proof of payment (PDF, PNG or JPEG, up to 4 MB)" wide><input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setProof(e.target.files?.[0]||null)}/></Field>{error&&<p className="error" role="alert">{error}</p>}<div className="form-footer"><button className="secondary" type="button" disabled={busy} onClick={async()=>{if(recordedId)await onSaved();onClose();}}>{recordedId?'Close':'Cancel'}</button><button className="primary" disabled={busy||!!recordedId&&!proof}>{busy?<Busy/>:recordedId?'Retry attachment':'Record payment'}</button></div></form></Modal>}
