'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Users,GitBranch,Building2,UserPlus,ArrowLeft,LogOut,Search,Download,RefreshCw} from 'lucide-react';
import {api,Field,Choice,Modal,Busy,Status} from './controls';
import {currencies} from '@/lib/money';
import {label,dateLabel} from '@/lib/presentation';

type Employee={id:string;personnel_code:string;name:string;email:string;department_id:string;department:string;position:string;team:string;manager_id:string|null;status:string;engagement:string;start_date:string};
type Department={id:string;name:string;code:string;head_id:string|null};
type Job={personnel_id:string;desired_email:string;state:string;last_error:string|null};
type Directory={profile:{id:string;full_name:string;role:string};own_person_id:string|null;people:Employee[];departments:Department[];next_sequence:number;onboarding:Job[];provisioning_configured?:boolean};
type Change={id:string;kind:'personal'|'payment';payload:Record<string,string>;status:string;created_at:string};
type Detail={employment:Record<string,any>|null;personal:Record<string,any>|null;payment:Record<string,any>|null;checklist:{id:string;title:string;done:boolean}[];requests:Change[]};
type AccountResult={complete:boolean;email:string;temporaryPassword:string|null;message?:string};
const personFields=[['personal_email','Personal email'],['phone','Phone number'],['date_of_birth','Date of birth'],['residential_address','Residential address'],['country_of_residence','Country of residence']] as const;
const bankFields=[['payment_method','Payment method'],['currency','Currency'],['bank_name','Bank or payment provider'],['account_holder','Account holder'],['account_number','Account number']] as const;
const display=(value:unknown)=>value===null||value===undefined||value===''?'Not provided':String(value);
const change=(action:string,input:unknown)=>api('/api/people',{method:'POST',body:JSON.stringify({action,input})});

export default function PeopleHub(){
 const [data,setData]=useState<Directory|null>(null),[error,setError]=useState(''),[view,setView]=useState('directory'),[search,setSearch]=useState(''),[department,setDepartment]=useState('all'),[status,setStatus]=useState('active'),[onboard,setOnboard]=useState(false),[selected,setSelected]=useState<string|null>(null),[head,setHead]=useState<Department|null>(null);
 const load=useCallback(async()=>{try{const response=await fetch('/api/session',{cache:'no-store'});const session:any=await response.json();if(!response.ok||!session.configured){location.replace('/login');return;}setData(await api<Directory>('/api/people'));setError('');}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load();},[load]);
 const admin=data?.profile.role==='super_admin';
 const people=(data?.people||[]).filter(p=>(department==='all'||p.department_id===department)&&(status==='all'||p.status===status)&&[p.name,p.personnel_code,p.position,p.email,p.team].some(v=>v.toLowerCase().includes(search.toLowerCase())));
 function exportDirectory(){
  const cell=(v:string)=>'"'+(/^[=+\-@\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';
  const lines=[['Employee ID','Name','Work email','Department','Job title','Team','Reports to','Status'],...people.map(p=>[p.personnel_code,p.name,p.email,p.department,p.position,p.team,data?.people.find(x=>x.id===p.manager_id)?.name||'',label(p.status)])];
  const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Aerinyu-employee-directory.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 if(!data)return <main className="login-pending"><div><p>{error||'Opening employee directory…'}</p>{error&&<button className="secondary" onClick={load}>Retry</button>}</div></main>;
 return <div className="people-shell"><aside className="people-sidebar"><a className="people-brand" href="/people"><img src="/aerinyu-logo.png" alt="Aerinyu Studios"/><span>AERINYU<small>STUDIOS</small></span></a><p className="eyebrow">PEOPLE</p><nav>{[['directory','Directory',Users],['departments','Departments',Building2],['chart','Organisation chart',GitBranch],...(admin?[['onboarding','Onboarding',UserPlus]]:[])].map(([key,title,Icon])=>{const I=Icon as typeof Users;return <button key={String(key)} className={view===key?'active':''} onClick={()=>setView(String(key))}><I size={18}/>{String(title)}</button>})}</nav><div className="people-nav-bottom">{data.own_person_id&&<button onClick={()=>setSelected(data.own_person_id)}>My profile</button>}{data.profile.role!=='employee'&&<a href="/">Finance workspace</a>}<span>{data.profile.full_name}<small>{label(data.profile.role)}</small></span><button onClick={async()=>{try{await api('/api/session',{method:'DELETE'});location.assign('/login')}catch(e){setError((e as Error).message)}}}><LogOut size={16}/> Sign out</button></div></aside>
 <main className="people-main"><header className="people-topbar"><span>Employee workspace</span><span>aerinyustudios.com</span></header><div className="people-content"><div className="page-heading"><div><p className="eyebrow">AERINYU STUDIOS</p><h1>{{directory:'People directory',departments:'Departments',chart:'Organisation chart',onboarding:'Employee onboarding'}[view]}</h1><p className="muted">{{directory:'Your team, their roles and how to reach them.',departments:'See who belongs to each department and who leads it.',chart:'Reporting relationships, generated from employee profiles.',onboarding:'Create employee records and company accounts in one place.'}[view]}</p></div>{admin&&<button className="primary" onClick={()=>setOnboard(true)}><UserPlus size={17}/> Onboard employee</button>}</div>
 {error&&<p role="alert" className="error">{error}</p>}
 <div className="people-stats"><div><strong>{data.people.filter(p=>p.status==='active').length}</strong><span>Active people</span></div><div><strong>{data.departments.length}</strong><span>Departments</span></div><div><strong>{data.people.filter(p=>p.status==='active'&&p.engagement==='employee').length}</strong><span>Employees</span></div>{admin&&<div><strong>{data.onboarding.filter(j=>j.state!=='complete').length}</strong><span>Accounts to complete</span></div>}</div>
 {(view==='directory'||view==='chart')&&<div className="toolbar people-filters"><div className="filter-search"><Search size={17}/><input aria-label="Search employees" placeholder="Search name, ID, title or email" value={search} onChange={e=>setSearch(e.target.value)}/></div><Choice label="Department filter" value={department} onChange={setDepartment} options={[{value:'all',label:'All departments'},...data.departments.map(d=>({value:d.id,label:d.name}))]}/><Choice label="Employment status filter" value={status} onChange={setStatus} options={['all','active','inactive','suspended','departed'].map(v=>({value:v,label:v==='all'?'All statuses':label(v)}))}/>{view==='directory'&&<button className="secondary" onClick={exportDirectory}><Download size={16}/> Export directory</button>}</div>}
 {view==='directory'&&<div className="panel people-table-wrap"><table className="people-table"><thead><tr>{['Employee','Department / role','Reports to','Work email','Status'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{people.map(p=><tr key={p.id}><td><button className="cell-link" onClick={()=>setSelected(p.id)}>{p.name}</button><small>{p.personnel_code}</small></td><td>{p.department}<small>{p.position}{p.team?' / '+p.team:''}</small></td><td>{data.people.find(x=>x.id===p.manager_id)?.name||'Not assigned'}</td><td><a href={'mailto:'+p.email}>{p.email}</a></td><td><Status value={p.status}/></td></tr>)}</tbody></table>{!people.length&&<div className="quiet-empty">No employees match these filters.</div>}</div>}
 {view==='departments'&&<div className="department-grid">{data.departments.map(d=>{const members=data.people.filter(p=>p.department_id===d.id&&p.status==='active');return <section className="panel department-card" key={d.id}><div className="section-line"><span className="eyebrow">{d.code||'DEPARTMENT'}</span><span>{members.length} active</span></div><h2>{d.name}</h2><p className="muted">Department head: {data.people.find(p=>p.id===d.head_id)?.name||'Not assigned'}</p>{members.map(p=><button className="department-member" key={p.id} onClick={()=>setSelected(p.id)}><strong>{p.name}</strong><span>{p.position}</span></button>)}<div className="people-actions"><button className="text-button" onClick={()=>{setDepartment(d.id);setSearch('');setStatus('active');setView('directory')}}>View department</button>{admin&&<button className="text-button" onClick={()=>setHead(d)}>Set department head</button>}</div></section>})}{!data.departments.length&&<p>No departments yet. Add one in Finance Administration.</p>}</div>}
 {view==='chart'&&<section className="panel org-panel"><div className="panel-heading"><h2>Reporting structure</h2><span className="muted">{people.length} people in this view</span></div><OrgChart people={people} all={data.people} open={setSelected}/><p className="chart-note">People without a manager in this view appear at the top. Set “Reports to” in an employee’s profile to connect them.</p></section>}
 {view==='onboarding'&&admin&&<><div className={'people-connection '+(data.provisioning_configured?'connected':'')}><strong>{data.provisioning_configured?'Google Workspace connection configured':'Connect Google Workspace to create company accounts'}</strong><p>{data.provisioning_configured?'Onboarding creates the Google account and prepares employee access. Google may require an available paid licence.':'Employee records and automatic IDs work now. Your administrator must configure the Google service account and Supabase server key before account creation can run.'}</p><span>Next employee sequence: {String(data.next_sequence).padStart(3,'0')}</span></div><div className="panel people-table-wrap"><table className="people-table"><thead><tr><th>Employee</th><th>Company email</th><th>Account setup</th><th/></tr></thead><tbody>{data.onboarding.map(j=><tr key={j.personnel_id}><td>{data.people.find(p=>p.id===j.personnel_id)?.name}</td><td>{j.desired_email}</td><td>{label(j.state)}{j.last_error&&<small className="error">{j.last_error}</small>}</td><td><button className="text-button" onClick={()=>setSelected(j.personnel_id)}>Open employee</button></td></tr>)}</tbody></table>{!data.onboarding.length&&<div className="quiet-empty">New employees will appear here as you onboard them.</div>}</div></>}
 </div><footer className="people-footer"><span>AERINYU STUDIOS</span><span>People and organisation</span></footer></main>
 {onboard&&<OnboardForm data={data} close={()=>setOnboard(false)} saved={async id=>{await load();setOnboard(false);setSelected(id);setView('onboarding')}}/>}
 {selected&&<EmployeeProfile id={selected} data={data} close={()=>setSelected(null)} reload={load}/>}
 {head&&<HeadForm department={head} people={data.people} close={()=>setHead(null)} saved={async()=>{await load();setHead(null)}}/>}
 </div>;
}

function OrgChart({people,all,open}:{people:Employee[];all:Employee[];open:(id:string)=>void}){
 const ids=new Set(people.map(p=>p.id));
 const roots=people.filter(p=>!p.manager_id||!ids.has(p.manager_id));
 const node=(p:Employee,path:Set<string>):React.ReactNode=>{
  if(path.has(p.id))return null;const next=new Set(path).add(p.id);const children=people.filter(x=>x.manager_id===p.id);
  return <li key={p.id}><button className="org-card" onClick={()=>open(p.id)}><span className="eyebrow">{p.department}</span><strong>{p.name}</strong><span>{p.position}</span><small>{p.personnel_code}</small>{p.manager_id&&!ids.has(p.manager_id)&&<small>Reports to {all.find(x=>x.id===p.manager_id)?.name||'another employee'}</small>}</button>{children.length>0&&<ul>{children.map(c=>node(c,next))}</ul>}</li>;
 };
 return <div className="org-scroll">{roots.length?<ul className="org-tree">{roots.map(p=>node(p,new Set()))}</ul>:<div className="quiet-empty">No reporting relationships to display for this selection.</div>}</div>;
}

function OnboardForm({data,close,saved}:{data:Directory;close:()=>void;saved:(id:string)=>Promise<void>}){
 const [v,setV]=useState({given_name:'',family_name:'',legal_name:'',display_name:'',email:'',engagement:'employee',department_id:data.departments[0]?.id||'',manager_id:'',position:'',team:'',start_date:new Date().toISOString().slice(0,10),currency:'MYR',personal_email:'',phone:'',date_of_birth:'',residential_address:'',country_of_residence:''});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const requestId=useRef(crypto.randomUUID());const emailEdited=useRef(false);const legalEdited=useRef(false);
 function set(key:string,value:string){setV(old=>{const next={...old,[key]:value};if(key==='given_name'||key==='family_name'){if(!emailEdited.current){const username=(next.given_name.slice(0,1)+next.family_name).normalize('NFKD').replace(/[^a-zA-Z0-9]/g,'').toLowerCase();next.email=username?username+'@aerinyustudios.com':'';}if(!legalEdited.current)next.legal_name=(next.given_name+' '+next.family_name).trim();}return next;});}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('/api/people/onboard',{method:'POST',body:JSON.stringify({action:'reserve',input:{...v,manager_id:v.manager_id||null,request_id:requestId.current}})});await saved(result.id);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal large title="Onboard employee" description="Save the employee record, then review and create the company account." onClose={()=>!busy&&close()}><form onSubmit={submit}><div className="people-id-notice"><strong>Employee ID assigned automatically</strong><span>Hire year + random two-digit number + sequence. Next sequence: {String(data.next_sequence).padStart(3,'0')}.</span></div><div className="form-grid">
 <Field label="Given names"><input required maxLength={200} value={v.given_name} onChange={e=>set('given_name',e.target.value)}/></Field><Field label="Family name"><input required maxLength={200} value={v.family_name} onChange={e=>set('family_name',e.target.value)}/></Field>
 <Field label="Full legal name"><input required value={v.legal_name} onChange={e=>{legalEdited.current=true;set('legal_name',e.target.value)}}/></Field><Field label="Preferred name"><input value={v.display_name} onChange={e=>set('display_name',e.target.value)}/></Field>
 <Field label="Company email" wide><input required type="email" value={v.email} onChange={e=>{emailEdited.current=true;set('email',e.target.value.toLowerCase())}}/><small>Review this address. You can use your preferred naming style.</small></Field>
 <Field label="Department"><Choice value={v.department_id} onChange={x=>set('department_id',x)} options={data.departments.map(d=>({value:d.id,label:d.name}))}/></Field><Field label="Job title"><input required value={v.position} onChange={e=>set('position',e.target.value)}/></Field>
 <Field label="Reports to"><Choice value={v.manager_id||'none'} onChange={x=>set('manager_id',x==='none'?'':x)} options={[{value:'none',label:'No manager assigned'},...data.people.filter(p=>p.status==='active').map(p=>({value:p.id,label:p.name}))]}/></Field><Field label="Team / unit"><input value={v.team} onChange={e=>set('team',e.target.value)}/></Field>
 <Field label="Employment type"><Choice value={v.engagement} onChange={x=>set('engagement',x)} options={['employee','contractor','freelancer','other']}/></Field><Field label="Hire date"><input required type="date" value={v.start_date} onChange={e=>set('start_date',e.target.value)}/></Field><Field label="Payment currency"><Choice value={v.currency} onChange={x=>set('currency',x)} options={[...currencies]}/></Field><Field label="Country of residence"><input value={v.country_of_residence} onChange={e=>set('country_of_residence',e.target.value)}/></Field>
 <Field label="Personal email"><input type="email" value={v.personal_email} onChange={e=>set('personal_email',e.target.value)}/></Field><Field label="Phone number"><input type="tel" value={v.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Date of birth"><input type="date" value={v.date_of_birth} onChange={e=>set('date_of_birth',e.target.value)}/></Field><Field label="Residential address"><textarea value={v.residential_address} onChange={e=>set('residential_address',e.target.value)}/></Field>
 </div>{error&&<p className="error" role="alert">{error}</p>}{!data.departments.length&&<p className="error">Add a department in Finance Administration first.</p>}<div className="form-footer"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button className="primary" disabled={busy||!v.department_id}>{busy?<Busy/>:'Save employee and continue'}</button></div></form></Modal>;
}

function EmployeeProfile({id,data,close,reload}:{id:string;data:Directory;close:()=>void;reload:()=>Promise<void>}){
 const person=data.people.find(p=>p.id===id)!;const admin=data.profile.role==='super_admin';const finance=admin||data.profile.role==='finance';const own=data.own_person_id===id;const job=data.onboarding.find(j=>j.personnel_id===id);
 const [detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(''),[account,setAccount]=useState<AccountResult|null>(null);
 const load=useCallback(async()=>{try{setDetail(await api('/api/people?id='+id));}catch(e){setError((e as Error).message)}},[id]);useEffect(()=>{void load();},[load]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await load();await reload();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal large title={person.name} description={person.personnel_code+' / '+person.department} onClose={()=>!busy&&close()}><div className="employee-profile"><div className="profile-grid">{[['Job title',person.position],['Company email',person.email],['Reports to',data.people.find(p=>p.id===person.manager_id)?.name||'Not assigned'],['Team / unit',person.team],['Employment type',label(person.engagement)],['Start date',dateLabel(person.start_date)]].map(([k,v])=><div key={k}><span>{k}</span><strong>{display(v)}</strong></div>)}</div>{admin&&<button className="secondary" onClick={()=>setEdit('employment')} disabled={!detail}>Edit employment and reporting line</button>}
 {error&&<p className="error" role="alert">{error}</p>}
 {admin&&job&&<section className="people-detail-section"><h3>Company account</h3><p>{job.desired_email}</p><p className="muted">{job.state==='complete'?'Google account created and employee portal access prepared.':job.last_error||'Create this employee’s Google Workspace account and employee portal access.'}</p>{job.state!=='complete'&&<><p className="muted">This creates a real company account. Google Workspace licensing and charges follow your subscription.</p><button className="primary" disabled={busy||!data.provisioning_configured} onClick={()=>run(async()=>{const result=await api<AccountResult>('/api/people/onboard',{method:'POST',body:JSON.stringify({action:'provision',personnel_id:id})});setAccount(result);})}>{busy?<Busy/>:job.state==='pending'?'Create company account':'Retry account setup'}</button>{!data.provisioning_configured&&<p className="muted">Google Workspace connection has not been configured yet.</p>}</>}
 {account&&<div className="account-result" role="status"><strong>{account.complete?'Account setup completed':'Employee saved; account setup needs attention'}</strong>{account.message&&<p>{account.message}</p>}{account.temporaryPassword?<><p>Temporary password. Copy it now and hand it to the employee securely. It is not stored in this app.</p><input aria-label="Temporary Google password" readOnly value={account.temporaryPassword}/><p>The employee must change this password at first sign-in.</p></>:account.complete&&<p>If the employee needs a password, reset it in Google Admin. This app does not retain passwords.</p>}</div>}</section>}
 {admin&&!job&&<section className="people-detail-section"><h3>Existing company account</h3><p className="muted">Link this employee to their existing Google Workspace account using {person.email}. Their employee ID and any existing administrator or finance role stay unchanged.</p><button className="secondary" disabled={busy||!data.provisioning_configured} onClick={()=>run(async()=>setAccount(await api<AccountResult>('/api/people/onboard',{method:'POST',body:JSON.stringify({action:'link',personnel_id:id})})))}>{busy?<Busy/>:'Link employee portal access'}</button>{account&&<p role="status">{account.message||'Employee portal access linked.'}</p>}{!data.provisioning_configured&&<p className="muted">Configure the Google Workspace connection to verify and link this account.</p>}</section>}
{!detail?<p className="muted">Loading profile…</p>:<>
 {(own||admin)&&<section className="people-detail-section"><div className="section-line"><h3>Personal details</h3><button className="text-button" onClick={()=>setEdit('personal')}>Request an update</button></div><div className="profile-grid">{personFields.map(([key,title])=><div key={key}><span>{title}</span><strong>{display(detail.personal?.[key])}</strong></div>)}</div></section>}
 {(own||finance)&&<section className="people-detail-section"><div className="section-line"><h3>Payment details</h3><button className="text-button" onClick={()=>setEdit('payment')}>Request an update</button></div><div className="profile-grid">{bankFields.map(([key,title])=><div key={key}><span>{title}</span><strong>{key==='payment_method'?label(detail.payment?.[key]||'bank_transfer'):display(detail.payment?.[key])}</strong></div>)}</div></section>}
 {detail.requests.length>0&&<section className="people-detail-section"><h3>Profile change requests</h3>{detail.requests.map(r=><div className="change-request" key={r.id}><div className="section-line"><strong>{r.kind==='personal'?'Personal details':'Payment details'}</strong><Status value={r.status}/></div><dl>{Object.entries(r.payload).map(([k,v])=><div key={k}><dt>{[...personFields,...bankFields].find(([key])=>key===k)?.[1]||label(k)}</dt><dd>{display(v)}</dd></div>)}</dl>{r.status==='pending'&&(admin||(finance&&r.kind==='payment'))&&<div className="people-actions"><button disabled={busy} className="primary" onClick={()=>run(()=>change('review',{id:r.id,decision:'approved'}))}>Approve change</button><button disabled={busy} className="secondary" onClick={()=>run(()=>change('review',{id:r.id,decision:'rejected'}))}>Reject</button></div>}</div>)}</section>}
 {detail.checklist.length>0&&<section className="people-detail-section"><h3>Onboarding checklist</h3>{detail.checklist.map(item=><label className="checklist-item" key={item.id}><input type="checkbox" checked={item.done} disabled={!admin||busy} onChange={e=>run(()=>change('checklist',{id:item.id,done:e.target.checked}))}/><span>{item.title}</span></label>)}</section>}
 </>}
 {admin&&person.status!=='active'&&<p className="people-connection">Employee portal access is disabled when employment is made inactive here. Suspend the Google account and remove access to other apps in their administrator consoles.</p>}
 </div>{edit&&detail&&(edit==='employment'?<EmploymentForm person={person} current={detail.employment!} data={data} close={()=>setEdit('')} saved={async()=>{setEdit('');await load();await reload()}}/>:<ChangeForm id={id} kind={edit as 'personal'|'payment'} current={edit==='personal'?detail.personal:detail.payment} close={()=>setEdit('')} saved={async()=>{setEdit('');await load();}}/>)}</Modal>;
}

function ChangeForm({id,kind,current,close,saved}:{id:string;kind:'personal'|'payment';current:Record<string,any>|null;close:()=>void;saved:()=>Promise<void>}){
 const fields=kind==='personal'?personFields:bankFields;const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(([k])=>[k,current?.[k]||(k==='currency'?'MYR':k==='payment_method'?'bank_transfer':'')])));const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Modal title={kind==='personal'?'Update personal details':'Update payment details'} description="Changes take effect after an authorised reviewer approves them." onClose={()=>!busy&&close()}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await change('change',{personnel_id:id,kind,payload:values});await saved();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{fields.map(([key,title])=><Field key={key} label={title}>{key==='currency'||key==='payment_method'?<Choice value={values[key]} onChange={v=>setValues({...values,[key]:v})} options={key==='currency'?[...currencies]:['bank_transfer','cash','wallet','other']}/>:<input type={key==='date_of_birth'?'date':key==='personal_email'?'email':'text'} value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})}/>}</Field>)}{error&&<p className="error">{error}</p>}<div className="form-footer"><button disabled={busy} className="primary">{busy?<Busy/>:'Submit for approval'}</button></div></form></Modal>;
}
function EmploymentForm({person,current,data,close,saved}:{person:Employee;current:Record<string,any>;data:Directory;close:()=>void;saved:()=>Promise<void>}){
 const [v,setV]=useState<Record<string,any>>({...current,end_date:current.end_date||'',manager_id:current.manager_id||'none'}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(key:string,value:string)=>setV({...v,[key]:value});
 return <Modal large title="Employment details" description={person.name+' / '+person.personnel_code} onClose={()=>!busy&&close()}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await change('employment',{...v,id:person.id,expected_version:current.version,manager_id:v.manager_id==='none'?null:v.manager_id});await saved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="form-grid">{[['legal_name','Full legal name'],['display_name','Preferred name'],['position','Job title'],['team','Team / unit']].map(([k,title])=><Field key={k} label={title}><input required={k==='legal_name'||k==='position'} value={v[k]} onChange={e=>set(k,e.target.value)}/></Field>)}<Field label="Department"><Choice value={v.department_id} onChange={x=>set('department_id',x)} options={data.departments.map(d=>({value:d.id,label:d.name}))}/></Field><Field label="Reports to"><Choice value={v.manager_id} onChange={x=>set('manager_id',x)} options={[{value:'none',label:'No manager assigned'},...data.people.filter(p=>p.id!==person.id&&p.status==='active').map(p=>({value:p.id,label:p.name}))]}/></Field><Field label="Employment type"><Choice value={v.engagement} onChange={x=>set('engagement',x)} options={['employee','contractor','freelancer','other']}/></Field><Field label="Status"><Choice value={v.status} onChange={x=>set('status',x)} options={['active','inactive','suspended','departed']}/></Field><Field label="End date"><input type="date" value={v.end_date} onChange={e=>set('end_date',e.target.value)}/></Field></div><p className="muted">Organisation changes update this hub. Google profile changes and account suspension remain managed in Google Admin.</p>{error&&<p className="error">{error}</p>}<div className="form-footer"><button disabled={busy} className="primary">{busy?<Busy/>:'Save employment details'}</button></div></form></Modal>;
}
function HeadForm({department,people,close,saved}:{department:Department;people:Employee[];close:()=>void;saved:()=>Promise<void>}){
 const [id,setId]=useState(department.head_id||'none'),[busy,setBusy]=useState(false),[error,setError]=useState('');return <Modal title="Department head" description={department.name} onClose={()=>!busy&&close()}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await change('head',{id:department.id,head_id:id==='none'?null:id});await saved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="Department head"><Choice value={id} onChange={setId} options={[{value:'none',label:'Not assigned'},...people.filter(p=>p.department_id===department.id&&p.status==='active').map(p=>({value:p.id,label:p.name}))]}/></Field>{error&&<p className="error">{error}</p>}<div className="form-footer"><button className="primary" disabled={busy}>{busy?<Busy/>:'Save department head'}</button></div></form></Modal>;
}

