'use client';
import {useState} from 'react';import {ArrowLeft,Download,FileCheck,Wallet,RotateCcw,Paperclip} from 'lucide-react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Field,Modal,Status,Busy,api,action,EmptyState,monthLabel} from './controls';
import {label,dateLabel,decimalLabel} from '@/lib/presentation';
import {PaymentForm} from './forms';
import {uploadProof} from './proof-upload';import {money,positive} from '@/lib/money';import type {RecordDetail,WorkspaceData,Doc,Activity,Payment} from '@/lib/types';
export function DocumentsTable({documents}:{documents:Doc[]}){return documents.length?<Table><TableHeader><TableRow>{['DOCUMENT','TYPE','ISSUED',''].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{documents.map(d=><TableRow key={d.id}><TableCell className="mono">{d.document_number}</TableCell><TableCell className="capitalize">{label(d.kind)}</TableCell><TableCell>{dateLabel(d.created_at)}</TableCell><TableCell><a className="text-button" href={'/api/documents/'+d.id}><Download size={15}/> PDF</a></TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="No documents generated" description="Approved statements and recorded payments can be issued as PDFs."/>}
export function Timeline({activity}:{activity:Activity[]}){return activity.length?<div className="timeline">{activity.map(a=><div className="activity-item" key={a.id}><div><strong>{label(a.action)}</strong><p>{a.actor_name} <span>{new Date(a.created_at).toLocaleString()}</span></p></div></div>)}</div>:<div className="quiet-empty">No activity to display.</div>}
export default function RecordView({detail,data,onBack,onEdit,onRefresh}:{detail:RecordDetail;data:WorkspaceData;onBack:()=>void;onEdit:()=>void;onRefresh:()=>Promise<void>}){
 const r=detail.record,p=r.snapshot||data.personnel.find(p=>p.id===r.personnel_id)!;const isFinance=['finance','super_admin'].includes(data.profile.role),canWrite=data.profile.role!=='viewer';const [busy,setBusy]=useState(false),[error,setError]=useState(''),[payment,setPayment]=useState(false),[confirm,setConfirm]=useState<{status?:string;paymentId?:string}|null>(null),[reason,setReason]=useState('');
 async function perform(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await onRefresh();setConfirm(null);setReason('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const transition=(status:string)=>perform(()=>action('transition',{id:r.id,expected_version:r.version,status,reason}));
 const generate=(kind:string,paymentId:string|null=null)=>perform(async()=>{const result=await api('/api/documents',{method:'POST',body:JSON.stringify({record_id:r.id,kind,payment_id:paymentId})});const a=document.createElement('a');a.href='/api/documents/'+result.id;a.click();});
 async function attach(id:string,file?:File){if(!file)return;await perform(async()=>{await uploadProof(id,file)})}
 return <><button className="text-button back" onClick={onBack}><ArrowLeft size={16}/> Work records</button><div className="page-heading"><div><p className="eyebrow">{r.statement_number}</p><h1>{p.legal_name}</h1><p className="muted">{p.personnel_code} / {p.position} / {monthLabel(r.period)}</p></div><Status value={r.status}/></div><div className="action-bar">
 {r.status==='draft'&&canWrite&&<><button className="secondary" disabled={busy} onClick={onEdit}>Edit draft</button><button className="primary" disabled={busy} onClick={()=>transition('submitted')}>Submit for review</button></>}
 {r.status==='submitted'&&isFinance&&<button className="primary" disabled={busy} onClick={()=>setConfirm({status:'approved'})}><FileCheck size={16}/> Approve statement</button>}
 {r.status==='approved'&&isFinance&&<button className="primary" disabled={busy} onClick={()=>transition('awaiting_payment')}>Queue for payment</button>}
 {['approved','awaiting_payment'].includes(r.status)&&isFinance&&positive(r.balance)&&<button className="primary" disabled={busy} onClick={()=>setPayment(true)}><Wallet size={16}/> Record payment</button>}
 {['approved','awaiting_payment','paid','archived'].includes(r.status)&&isFinance&&<button className="secondary" disabled={busy} onClick={()=>generate('statement')}><Download size={16}/> Generate statement PDF</button>}
 {((r.status==='submitted'&&canWrite)||(['approved','awaiting_payment'].includes(r.status)&&isFinance))&&<button className="text-button" disabled={busy} onClick={()=>setConfirm({status:'draft'})}>Request revision</button>}
 {r.status==='paid'&&isFinance&&<button className="secondary" disabled={busy} onClick={()=>transition('archived')}>Archive record</button>}{busy&&<Busy/>}</div>{error&&<p className="error" role="alert">{error}</p>}
 <section className="metrics detail-metrics">{[['Total payable',r.total],['Amount paid',r.paid],['Remaining balance',r.balance]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{money(value,r.currency)}</strong><small>{label==='Remaining balance'?'Updated after every payment':monthLabel(r.period)}</small></div>)}</section>
 <Tabs defaultValue="work" className="record-tabs"><TabsList variant="line"><TabsTrigger value="work">Work & compensation</TabsTrigger>{isFinance&&<TabsTrigger value="payments">Payments ({detail.payments.length})</TabsTrigger>}{isFinance&&<TabsTrigger value="documents">Documents ({detail.documents.length})</TabsTrigger>}<TabsTrigger value="activity">Activity</TabsTrigger></TabsList><TabsContent value="work"><div className="panel"><div className="panel-heading"><h2>Work summary</h2><span className="muted">{p.department} / {label(p.engagement)}</span></div><Table><TableHeader><TableRow>{['DATE / PROJECT','TASK / DELIVERABLE','QTY / HRS','RATE','AMOUNT'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{detail.items.map((i,n)=><TableRow key={n}><TableCell>{dateLabel(i.completed_on)}<small>{i.project||'No project'}</small></TableCell><TableCell><strong>{i.title}</strong><small className="wrap">{i.description}</small>{i.notes&&<small className="wrap">Notes: {i.notes}</small>}</TableCell><TableCell>{i.calculation==='fixed'?'':decimalLabel(i.quantity)}</TableCell><TableCell>{i.calculation==='fixed'?'':decimalLabel(i.rate)}</TableCell><TableCell className="amount">{money(i.amount||'0',r.currency)}</TableCell></TableRow>)}</TableBody></Table>{detail.adjustments.length>0&&<><div className="panel-heading"><h2>Adjustments</h2></div><Table><TableBody>{detail.adjustments.map((a,i)=><TableRow key={i}><TableCell className="capitalize">{label(a.kind)}</TableCell><TableCell>{a.description}<small>{a.notes}</small></TableCell><TableCell className="amount">{a.kind==='deduction'?'− ':''}{money(a.amount,r.currency)}</TableCell></TableRow>)}</TableBody></Table></>}<div className="summary-grid"><div><h3>Notes</h3><p>{r.notes||'No additional notes.'}</p>{r.approved_at&&<p className="approval-note">Approved by {r.approved_by_name}<br/>{new Date(r.approved_at).toLocaleString()}</p>}</div><dl>{[['Work subtotal',r.work_subtotal],['Additional compensation',r.additional],['Reimbursements',r.reimbursements],['Deductions',r.deductions],['Total payable',r.total]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v,r.currency)}</dd></div>)}</dl></div></div></TabsContent>
 <TabsContent value="payments"><div className="panel"><div className="panel-heading"><h2>Payment history</h2><span className="muted">Reversed payments remain in the audit trail.</span></div>{detail.payments.length?<Table><TableHeader><TableRow>{['DATE / REFERENCE','METHOD','AMOUNT','STATUS','DOCUMENTS / ACTIONS'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{detail.payments.map(p=><TableRow key={p.id}><TableCell>{dateLabel(p.payment_date)}<small>{p.reference}</small></TableCell><TableCell>{label(p.method)}<small>{p.paying_account}</small></TableCell><TableCell>{money(p.amount,r.currency)}</TableCell><TableCell><Status value={p.reversed_at?'reversed':'recorded'}/>{p.reversal_reason&&<small className="wrap">{p.reversal_reason}</small>}</TableCell><TableCell><div className="row-actions">{!p.reversed_at&&<><button className="text-button" disabled={busy} onClick={()=>generate('receipt',p.id)}><Download size={14}/> Receipt</button><button className="text-button danger" disabled={busy} onClick={()=>setConfirm({paymentId:p.id})}><RotateCcw size={14}/> Reverse</button></>}{p.proof_path?<a className="text-button" href={'/api/proofs/'+p.id}><Paperclip size={14}/> Proof</a>:<label className="text-button upload-label"><Paperclip size={14}/> Attach proof<input disabled={busy} type="file" accept="application/pdf,image/png,image/jpeg" onChange={async e=>{const input=e.currentTarget;await attach(p.id,input.files?.[0]);input.value='';}}/></label>}</div></TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="No payments recorded" description="Record a full or partial payment after approval."/>}</div></TabsContent>
 <TabsContent value="documents"><div className="panel"><DocumentsTable documents={detail.documents}/></div></TabsContent><TabsContent value="activity"><div className="panel"><Timeline activity={detail.activity}/></div></TabsContent></Tabs>
 {payment&&<PaymentForm record={r} onClose={()=>setPayment(false)} onSaved={onRefresh}/>}{confirm&&<Modal title={confirm.paymentId?'Reverse payment':confirm.status==='approved'?'Approve statement':'Request a revision'} description={confirm.status==='approved'?'Approval locks the financial fields and saves the personnel snapshot.':confirm.paymentId?'The original payment and receipts will remain in history. The balance will be reopened.':'This returns the record to draft and keeps previously generated documents in history.'} onClose={()=>!busy&&setConfirm(null)}>{confirm.status!=='approved'&&<Field label="Reason (at least 10 characters)"><textarea minLength={10} required value={reason} onChange={e=>setReason(e.target.value)}/></Field>}{error&&<p className="error">{error}</p>}<div className="form-footer"><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button className="primary" disabled={busy||(confirm.status!=='approved'&&reason.trim().length<10)} onClick={()=>confirm.paymentId?perform(()=>action('reverse_payment',{id:confirm.paymentId,reason})):transition(confirm.status!)}>{busy?<Busy/>:'Confirm'}</button></div></Modal>}</>
}
