'use client';
import {useMemo,useState} from 'react';import {Download} from 'lucide-react';import Decimal from 'decimal.js';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Choice,Field,EmptyState,api,monthLabel} from './controls';import {money,sum,csvCell} from '@/lib/money';import type {WorkspaceData} from '@/lib/types';
export default function Reports({data}:{data:WorkspaceData|null}){const [type,setType]=useState('monthly'),[from,setFrom]=useState(new Date().getFullYear()+'-01'),[to,setTo]=useState(new Date().toISOString().slice(0,7)),[projectRows,setProjectRows]=useState<{label:string;currency:string;amount:string}[]|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const rows=useMemo(()=>{if(!data)return [];const records=data.records.filter(r=>r.period.slice(0,7)>=from&&r.period.slice(0,7)<=to&&r.status!=='draft'&&r.status!=='submitted');const grouped=new Map<string,{label:string;currency:string;amount:string}>();const add=(label:string,currency:string,amount:string)=>{const k=label+'|'+currency;const prev=grouped.get(k);grouped.set(k,{label,currency,amount:sum([prev?.amount||'0',amount])})};if(type==='payments'){data.payments.filter(p=>!p.reversed_at&&p.payment_date.slice(0,7)>=from&&p.payment_date.slice(0,7)<=to).forEach(p=>{const r=data.records.find(r=>r.id===p.record_id);if(r)add(monthLabel(p.payment_date),r.currency,p.amount)});}else records.forEach(r=>{const person=r.snapshot||data.personnel.find(p=>p.id===r.personnel_id);if(type==='outstanding'){if(new Decimal(r.balance).gt(0))add(r.statement_number+' / '+person?.legal_name,r.currency,r.balance)}else if(type==='department')add(person?.department||'Unassigned',r.currency,r.total);else if(type==='personnel')add(person?.personnel_code+' / '+person?.legal_name,r.currency,r.paid);else add(monthLabel(r.period),r.currency,r.total)});return [...grouped.values()];},[data,type,from,to]);
 const displayed=type==='project'?projectRows||[]:rows;
 async function project(){setLoading(true);setError('');try{const result=await api('/api/reports',{method:'POST',body:JSON.stringify({from:from+'-01',to:to+'-01'})});setProjectRows(result.rows)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 function csv(){const csv=[['Group','Currency','Amount'],...displayed.map(r=>[r.label,r.currency,r.amount])].map(r=>r.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aerinyu-${type}-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url)}
 return <><div className="panel report-filters"><Field label="Report"><Choice value={type} onChange={setType} options={[{value:'monthly',label:'Monthly personnel expenditure'},{value:'payments',label:'Payments by month'},{value:'outstanding',label:'Outstanding payments'},{value:'project',label:'Expenditure by project'},{value:'department',label:'Expenditure by department'},{value:'personnel',label:'Personnel payment history'}]}/></Field><Field label="From"><input type="month" value={from} onChange={e=>{setFrom(e.target.value);setProjectRows(null)}}/></Field><Field label="To"><input type="month" value={to} onChange={e=>{setTo(e.target.value);setProjectRows(null)}}/></Field>{type==='project'&&<button className="primary" disabled={!data||loading||from>to} onClick={project}>{loading?'Loading…':'Run report'}</button>}<button className="secondary" disabled={!displayed.length||from>to} onClick={csv}><Download size={16}/> Export CSV</button></div><p className="muted report-note">Approved records only. Currencies are reported separately. Project expenditure includes work-item amounts; record-level adjustments are not allocated to projects. Personnel history uses reporting periods; payment reports use payment dates.</p>{from>to&&<p className="error">The end month must be on or after the start month.</p>}{error&&<p className="error">{error}</p>}<div className="panel">{displayed.length?<Table><TableHeader><TableRow><TableHead>GROUP</TableHead><TableHead>CURRENCY</TableHead><TableHead>AMOUNT</TableHead></TableRow></TableHeader><TableBody>{displayed.map((r,i)=><TableRow key={i}><TableCell>{r.label}</TableCell><TableCell>{r.currency}</TableCell><TableCell className="amount">{money(r.amount,r.currency)}</TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="No report data" description={type==='project'?'Select a date range and run the report.':'Records in the selected period will appear here.'}/>}</div></>
}
