'use client';
import {useEffect,useState,useCallback,FormEvent} from 'react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {CommandDialog,CommandInput,CommandList,CommandGroup,CommandItem,CommandEmpty} from '@/components/ui/command';
import {Skeleton} from '@/components/ui/skeleton';
import {LayoutDashboard,Users,Files,Wallet,FolderOpen,Briefcase,ChartNoAxesCombined,Settings,Search,Plus,ArrowUpRight,ShieldCheck,LockKeyhole,ChevronRight,LogOut,RefreshCw,Download} from 'lucide-react';
import {Choice,Field,Modal,EmptyState,Status,Busy,api,action,monthLabel} from './controls';
import {PersonnelForm,RecordEditor} from './forms';
import RecordView,{DocumentsTable,Timeline} from './record-detail';
import Reports from './reports';
import PaymentDetails from './payment-details';
import {money,sum} from '@/lib/money';
import {label,dateLabel} from '@/lib/presentation';
import type {WorkspaceData,Person,RecordDetail,RecordRow} from '@/lib/types';
const navigation=[['Overview',LayoutDashboard,'/'],['Personnel',Users,'/personnel'],['Work Records',Files,'/work-records'],['Payments',Wallet,'/payments'],['Documents',FolderOpen,'/documents'],['Projects',Briefcase,'/projects'],['Reports',ChartNoAxesCombined,'/reports'],['Administration',Settings,'/administration']] as const;
const descriptions:Record<string,string>={'Overview':'Your people, work and payments. In one place.','Personnel':'The central directory for your team and external collaborators.','Work Records':'Monthly deliverables, compensation and approvals.','Payments':'Recorded transactions and outstanding balances.','Documents':'Statements and receipts, securely stored with their history.','Projects':'Projects associated with your team’s work.','Reports':'Expenditure, payment history and outstanding amounts.','Administration':'Departments, workspace access and configuration.'};
export default function Workspace({initialPage='Overview'}:{initialPage?:string}){
 const [page,setPage]=useState(initialPage),[data,setData]=useState<WorkspaceData|null>(null),[configured,setConfigured]=useState<boolean|null>(null),[signedIn,setSignedIn]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[status,setStatus]=useState('all'),[command,setCommand]=useState(false);
 const [personForm,setPersonForm]=useState<Person|'new'|null>(null),[selectedPerson,setSelectedPerson]=useState<Person|null>(null),[detail,setDetail]=useState<RecordDetail|null>(null),[editing,setEditing]=useState(false),[recordLoading,setRecordLoading]=useState(false),[directory,setDirectory]=useState<{kind:string;id:string|null;name:string;status:string;code?:string|null}|null>(null),[profileForm,setProfileForm]=useState<{id:string;full_name:string;role:string;active:boolean}|null>(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 const finance=!!data&&['finance','super_admin'].includes(data.profile.role),canWrite=!!data&&data.profile.role!=='viewer';
 const load=useCallback(async()=>{setError('');try{const response=await fetch('/api/session',{cache:'no-store'});const session:any=await response.json();if(session.configured===false){setConfigured(false);setSignedIn(false);setData(null);location.replace('/login');return;}setConfigured(true);if(!response.ok){setSignedIn(false);setData(null);location.replace('/login'+(response.status===403?'?error=access':''));return;}if(session.profile?.role==='employee'){location.replace('/people');return;}setSignedIn(true);const d=await api('/api/workspace');setData(d);}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setCommand(v=>!v)}};const pop=()=>{setPage(navigation.find(n=>n[2]===location.pathname)?.[0]||'Overview');setDetail(null);setEditing(false)};window.addEventListener('keydown',key);window.addEventListener('popstate',pop);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('popstate',pop)}},[load]);
 function navigate(next:string){setPage(next);setSearch('');setStatus('all');setDetail(null);setEditing(false);const path=navigation.find(n=>n[0]===next)?.[2];if(path&&location.pathname!==path)history.pushState({},'',path);}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_monthly_record',description:'Open the monthly work-record editor. Does not create or save a record.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');if(!canWrite)throw Error('Sign in with record-creation permission first.');navigate('Work Records');setEditing(true);return {editor:'monthly_record',saved:false};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[canWrite]);
 async function openRecord(id:string){setSelectedPerson(null);setCommand(false);navigate('Work Records');setRecordLoading(true);setError('');try{setDetail(await api('/api/records/'+id))}catch(e){setError((e as Error).message)}finally{setRecordLoading(false)}}
 async function refreshRecord(){await load();if(detail)setDetail(await api('/api/records/'+detail.record.id))}
 async function signOut(){setSaving(true);try{await api('/api/session',{method:'DELETE'});setData(null);setSignedIn(false);setDetail(null);setSelectedPerson(null);setEditing(false);location.assign('/login')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 const match=(...values:unknown[])=>values.some(v=>String(v||'').toLowerCase().includes(search.toLowerCase()));
 const personFor=(r:RecordRow)=>r.snapshot||data?.personnel.find(p=>p.id===r.personnel_id);
 const records=(data?.records||[]).filter(r=>(!month||r.period.startsWith(month))&&(status==='all'||r.status===status)&&match(r.statement_number,personFor(r)?.legal_name,personFor(r)?.personnel_code));
 const totalRecords=(data?.records||[]).filter(r=>r.period.startsWith(month));
 const amounts=(kind:'total'|'paid')=>{const groups=new Map<string,string[]>();if(kind==='total')totalRecords.forEach(r=>groups.set(r.currency,[...(groups.get(r.currency)||[]),r.total]));else data?.payments.filter(p=>!p.reversed_at&&p.payment_date.startsWith(month)).forEach(p=>{const r=data.records.find(r=>r.id===p.record_id);if(r)groups.set(r.currency,[...(groups.get(r.currency)||[]),p.amount])});return [...groups].map(([c,v])=>money(sum(v),c));};
 const newRecord=()=>{navigate('Work Records');setEditing(true)};
 const recordTable=(rows:RecordRow[])=>rows.length?<Table><TableHeader><TableRow>{['PERSONNEL','REPORTING PERIOD','STATEMENT','TOTAL PAYABLE','STATUS',''].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell><button className="cell-link" onClick={()=>openRecord(r.id)}>{personFor(r)?.legal_name}</button><small>{personFor(r)?.personnel_code} / {personFor(r)?.department}</small></TableCell><TableCell>{monthLabel(r.period)}</TableCell><TableCell className="mono">{r.statement_number}</TableCell><TableCell className="amount">{money(r.total,r.currency)}</TableCell><TableCell><Status value={r.status}/></TableCell><TableCell><button className="icon-button" aria-label={'Open '+r.statement_number} onClick={()=>openRecord(r.id)}><ArrowUpRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table>:<EmptyState title={data?'No work records in this view':'Your records will appear here'} description={data?'Create a monthly record, or adjust the reporting month and status filters.':'Connect the workspace, add personnel, then create your first monthly record.'}/>;
 async function saveDirectory(e:FormEvent){e.preventDefault();setSaving(true);setFormError('');try{await action('directory',{...directory,...(directory?.kind==='department'?{code:directory.code}:{})});await load();setDirectory(null)}catch(e){setFormError((e as Error).message)}finally{setSaving(false)}}
 async function saveProfile(e:FormEvent){e.preventDefault();setSaving(true);setFormError('');try{await action('profile',profileForm);await load();setProfileForm(null)}catch(e){setFormError((e as Error).message)}finally{setSaving(false)}}
 const newDirectory=(kind:string)=>{setFormError('');setDirectory({kind,id:null,name:'',status:'active',...(kind==='department'?{code:''}:{})})};
 const unavailable=!data?'Connect and sign in to the workspace to continue.':undefined;
 if(!data)return <main className="login-pending"><p>{error||'Opening workspace…'}</p></main>;
 return <SidebarProvider><Sidebar className="studio-sidebar"><SidebarHeader><div className="brand"><img className="brand-logo" src="/aerinyu-logo.png" alt="Aerinyu Studios logo" width={56} height={56}/><span>AERINYU<span className="brand-sub">STUDIOS</span></span></div></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><a className="nav-item" href="/people"><Users size={18}/> People hub</a>{navigation.map(([label,Icon,path])=><a href={path} key={label} onClick={e=>{e.preventDefault();navigate(label)}} aria-current={page===label?'page':undefined} className={'nav-item '+(page===label?'active':'')}><Icon size={18}/>{label}{page===label&&<ChevronRight size={14}/>}</a>)}</SidebarContent><SidebarFooter><div className="private-label"><ShieldCheck size={15}/> Private workspace</div><div className="account"><span className="avatar">{data?data.profile.full_name.split(' ').map(s=>s[0]).slice(0,2).join(''):'AS'}</span><span>{data?.profile.full_name||'Aerinyu Studios'}<small>{(data?label(data.profile.role):'')||(configured?'Sign in required':'Setup required')}</small></span><button aria-label="Workspace settings" className="icon-button" onClick={()=>navigate('Administration')}><Settings size={16}/></button></div>{signedIn&&<button className="nav-item" disabled={saving} onClick={signOut}><LogOut size={16}/> Sign out</button>}</SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Workspace</span><ChevronRight size={14}/><strong>{page}</strong></div><button className="global-search" onClick={()=>setCommand(true)}><Search size={16}/><span>Search workspace</span><kbd>Ctrl K</kbd></button><span className="top-note"><LockKeyhole size={13}/> INTERNAL</span></header><div className="page">
 {editing&&data?<RecordEditor data={data} detail={detail||undefined} onClose={()=>setEditing(false)} onSaved={async id=>{await load();setEditing(false);await openRecord(id)}}/>:detail&&data?<RecordView detail={detail} data={data} onBack={()=>setDetail(null)} onEdit={()=>setEditing(true)} onRefresh={refreshRecord}/>:<>
 <div className="page-heading"><div><p className="eyebrow">FINANCE & OPERATIONS</p><h1>{page==='Overview'?'Workspace overview':page}</h1><p className="muted">{descriptions[page]}</p></div>{(page==='Overview'||page==='Work Records')&&<button className="primary" disabled={!canWrite} title={unavailable} onClick={newRecord}><Plus size={17}/> New monthly record</button>}{page==='Personnel'&&<button className="primary" disabled={!finance} title={unavailable} onClick={()=>setPersonForm('new')}><Plus size={17}/> Add personnel</button>}{page==='Projects'&&<button className="primary" disabled={!finance} onClick={()=>newDirectory('project')}><Plus size={17}/> Add project</button>}</div>
 {error&&<div className="error" role="alert">{error} <button className="text-button" onClick={load}><RefreshCw size={14}/> Retry</button></div>}
 {configured===false&&<div className="setup-notice"><ShieldCheck size={20}/><div><strong>Connect your private workspace</strong><p>Supabase configuration is required before personnel and financial records can be accessed.</p></div>{page!=='Administration'&&<button className="text-button" onClick={()=>navigate('Administration')}>View setup <ArrowUpRight size={16}/></button>}</div>}
 {loading||recordLoading?<div className="loading-grid" aria-label="Loading workspace"><Skeleton className="h-36"/><Skeleton className="h-72"/></div>:<>
 {page==='Overview'&&<><div className="section-line"><h2>Monthly position</h2><input className="period" aria-label="Reporting month" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><section className="metrics">{[['Active personnel',data?String(data.personnel.filter(p=>p.status==='active').length):'Pending','Across all departments'],['Statements in progress',data?String(totalRecords.filter(r=>r.status==='draft'||r.status==='submitted').length):'Pending','Drafts and review queue'],['Total payable',data?(amounts('total').join('\n')||'No records'):'Pending','All statements in reporting month'],['Paid this month',data?(finance?(amounts('paid').join('\n')||'No payments'):'Restricted'):'Pending','By payment date / each currency']].map(([label,value,note])=><div className="metric" key={label}><span>{label}</span><strong className={!data||value.length>14?'compact-value':''}>{value}</strong><small>{note}</small></div>)}</section><div className="panel overview-records"><div className="panel-heading"><div><h2>Work records</h2><p className="muted">Monthly statements and their current status.</p></div><button className="text-button" onClick={()=>navigate('Work Records')}>View all records <ArrowUpRight size={16}/></button></div>{recordTable(records.slice(0,5))}</div><div className="bottom-grid"><section className="panel"><div className="panel-heading"><h2>Recent activity</h2><span className="subtle">LATEST UPDATES</span></div><Timeline activity={data?.activity.slice(0,5)||[]}/></section><section className="panel"><div className="panel-heading"><h2>Generated documents</h2><button className="text-button" onClick={()=>navigate('Documents')}>View all <ArrowUpRight size={15}/></button></div>{data?.documents.length?<div className="recent-docs">{data.documents.slice(0,4).map(d=><a key={d.id} href={'/api/documents/'+d.id}><Files size={18}/><span>{d.document_number}<small>{label(d.kind)}</small></span><Download size={15}/></a>)}</div>:<div className="quiet-empty">No generated documents to display.</div>}</section></div></>}
 {page==='Personnel'&&<><div className="toolbar"><div className="filter-search"><Search size={16}/><input aria-label="Search personnel" placeholder="Search ID, name or department…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Choice label="Personnel status" value={status} onChange={setStatus} options={['all','active','inactive','suspended','departed'].map(v=>({value:v,label:v==='all'?'All statuses':label(v)}))}/><span className="muted">{data?.personnel.length||0} personnel</span></div><div className="panel">{data?.personnel.filter(p=>(status==='all'||p.status===status)&&match(p.personnel_code,p.legal_name,p.department)).length?<Table><TableHeader><TableRow>{['PERSONNEL','DEPARTMENT / POSITION','ENGAGEMENT','CURRENCY','STATUS',''].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{data.personnel.filter(p=>(status==='all'||p.status===status)&&match(p.personnel_code,p.legal_name,p.department)).map(p=><TableRow key={p.id}><TableCell><button className="cell-link" onClick={()=>setSelectedPerson(p)}>{p.display_name||p.legal_name}</button><small className="mono">{p.personnel_code}</small></TableCell><TableCell>{p.department}<small>{p.position}</small></TableCell><TableCell className="capitalize">{label(p.engagement)}</TableCell><TableCell>{p.currency}</TableCell><TableCell><Status value={p.status}/></TableCell><TableCell><button className="icon-button" aria-label={'View '+p.legal_name} onClick={()=>setSelectedPerson(p)}><ArrowUpRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="No personnel found" description={data?'Add a person to your directory or change the search filters.':'Your personnel directory will be available after setup.'}/>}</div></>}
 {page==='Work Records'&&<><div className="toolbar"><div className="filter-search"><Search size={16}/><input aria-label="Search work records" placeholder="Search name, employee ID or statement…" value={search} onChange={e=>setSearch(e.target.value)}/></div><input className="period" aria-label="Record reporting month" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><Choice label="Record status" value={status} onChange={setStatus} options={['all','draft','submitted','approved','awaiting_payment','paid','archived'].map(v=>({value:v,label:v==='all'?'All statuses':label(v)}))}/><button className="text-button" onClick={()=>{setMonth('');setStatus('all');setSearch('')}}>Clear filters</button></div><div className="panel">{recordTable(records)}</div></>}
 {page==='Payments'&&(data&&!finance?<EmptyState title="Finance access required" description="Payment transaction details are restricted to finance and administrators."/>:<><Tabs defaultValue="outstanding"><TabsList variant="line"><TabsTrigger value="outstanding">Outstanding balances</TabsTrigger><TabsTrigger value="history">Payment history</TabsTrigger></TabsList><TabsContent value="outstanding"><div className="panel">{recordTable((data?.records||[]).filter(r=>['approved','awaiting_payment'].includes(r.status)))}</div></TabsContent><TabsContent value="history"><div className="toolbar"><div className="filter-search"><Search size={16}/><input aria-label="Search payments" placeholder="Transaction or receipt reference…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="panel">{data?.payments.filter(p=>match(p.reference,p.receipt_number)).length?<Table><TableHeader><TableRow>{['DATE','RECIPIENT','TRANSACTION REFERENCE','AMOUNT','STATUS',''].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{data.payments.filter(p=>match(p.reference,p.receipt_number)).map(p=>{const r=data.records.find(r=>r.id===p.record_id)!;return <TableRow key={p.id}><TableCell>{dateLabel(p.payment_date)}</TableCell><TableCell>{personFor(r)?.legal_name}<small>{p.receipt_number}</small></TableCell><TableCell>{p.reference}</TableCell><TableCell>{money(p.amount,r.currency)}</TableCell><TableCell><Status value={p.reversed_at?'reversed':'recorded'}/></TableCell><TableCell><button className="text-button" onClick={()=>openRecord(p.record_id)}>Open record <ArrowUpRight size={14}/></button></TableCell></TableRow>})}</TableBody></Table>:<EmptyState title="No payment transactions" description="Recorded payments will appear here with their references and receipts."/>}</div></TabsContent></Tabs></>)}
 {page==='Documents'&&(data&&!finance?<EmptyState title="Finance access required" description="Financial document access is restricted to finance and administrators."/>:<><div className="toolbar"><div className="filter-search"><Search size={16}/><input aria-label="Search documents" placeholder="Search document number…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="panel"><DocumentsTable documents={data?.documents.filter(d=>match(d.document_number))||[]}/></div></>)}
 {page==='Projects'&&<div className="panel">{data?.projects.length?<Table><TableHeader><TableRow><TableHead>PROJECT</TableHead><TableHead>STATUS</TableHead><TableHead>ACTIONS</TableHead></TableRow></TableHeader><TableBody>{data.projects.map(p=><TableRow key={p.id}><TableCell>{p.name}</TableCell><TableCell><Status value={p.status}/></TableCell><TableCell>{finance&&<button className="text-button" onClick={()=>{setFormError('');setDirectory({...p,kind:'project'})}}>Edit project</button>}</TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="No projects yet" description="Add projects to categorize deliverables and report expenditure."/>}</div>}
 {page==='Reports'&&(data&&!finance?<EmptyState title="Finance access required" description="Expenditure reports are restricted to finance and administrators."/>:<Reports data={data}/>)}
 {page==='Administration'&&<><section className="panel setup-panel"><div className="panel-heading"><h2>Workspace connection</h2><Status value={data?'connected':configured?'sign_in_required':'setup_required'}/></div><div className="setup-body"><div><span className="setup-step">01</span><h3>Private database</h3><p>Configure the Supabase project URL and publishable or anon key in the server environment. Apply the included database migrations.</p></div><div><span className="setup-step">02</span><h3>Authorized accounts</h3><p>Use company Google Workspace accounts. An administrator must authorize each account and assign a role.</p></div><div><span className="setup-step">03</span><h3>Begin operations</h3><p>Create departments, add personnel, then prepare monthly work records. No demo data is loaded into this workspace.</p></div></div><div className="setup-footer"><ShieldCheck size={16}/><span>Financial documents and payment proofs use private storage. No service-role key is required by this application.</span><button className="text-button" onClick={load}><RefreshCw size={14}/> Check connection</button></div></section>
 {data&&<><section className="panel admin-panel"><div className="panel-heading"><h2>Departments</h2>{finance&&<button className="secondary" onClick={()=>newDirectory('department')}><Plus size={15}/> Add department</button>}</div>{data.departments.length?<Table><TableBody>{data.departments.map(d=><TableRow key={d.id}><TableCell>{d.name}<small>{d.code||'Receipt code required'}</small></TableCell><TableCell>{finance&&<button className="text-button" onClick={()=>{setFormError('');setDirectory({...d,kind:'department',status:'active'})}}>Edit</button>}</TableCell></TableRow>)}</TableBody></Table>:<div className="quiet-empty">Add a department before creating personnel.</div>}</section>{data.profile.role==='super_admin'&&<section className="panel admin-panel"><div className="panel-heading"><div><h2>Workspace access</h2><p className="muted">Authorize company Google Workspace accounts and assign their access level.</p></div><button className="secondary" onClick={()=>{setFormError('');setProfileForm({id:'',full_name:'',role:'viewer',active:true})}}><Plus size={15}/> Authorize account</button></div><Table><TableHeader><TableRow><TableHead>NAME</TableHead><TableHead>ROLE</TableHead><TableHead>STATUS</TableHead><TableHead/></TableRow></TableHeader><TableBody>{data.profiles.map(p=><TableRow key={p.id}><TableCell>{p.full_name}</TableCell><TableCell>{label(p.role)}</TableCell><TableCell><Status value={p.active?'active':'inactive'}/></TableCell><TableCell><button className="text-button" onClick={()=>{setFormError('');setProfileForm(p)}}>Edit access</button></TableCell></TableRow>)}</TableBody></Table></section>}<section className="panel admin-panel"><div className="panel-heading"><h2>Your account</h2></div><div className="setup-footer"><span>{data.profile.full_name} / {label(data.profile.role)}</span><button className="text-button" onClick={signOut}><LogOut size={15}/> Sign out</button></div></section></>}
 </>}
 </>}</>}
 <footer className="page-footer"><span>AERINYU STUDIOS</span><span>Personnel & compensation management</span><span>Private / Internal</span></footer></div></main>
 {personForm&&data&&<PersonnelForm person={personForm==='new'?undefined:personForm} data={data} onClose={()=>setPersonForm(null)} onSaved={load}/>}
 {selectedPerson&&data&&<Sheet open onOpenChange={v=>!v&&setSelectedPerson(null)}><SheetContent className="person-sheet"><SheetHeader><SheetTitle>{selectedPerson.legal_name}</SheetTitle><SheetDescription>{selectedPerson.personnel_code} / {selectedPerson.position}</SheetDescription></SheetHeader><Tabs defaultValue="overview"><TabsList variant="line">{['overview','work records','payments','documents','activity'].map(t=><TabsTrigger key={t} value={t}>{label(t)}</TabsTrigger>)}</TabsList><TabsContent value="overview"><div className="profile-grid">{[['Employee ID',selectedPerson.personnel_code],['Department',selectedPerson.department],['Engagement',label(selectedPerson.engagement)],['Email',selectedPerson.email],['Phone',selectedPerson.phone||'Not provided'],['Hire date',dateLabel(selectedPerson.start_date)],['Status',label(selectedPerson.status)],['Currency',selectedPerson.currency],['Default rate',money(selectedPerson.default_rate,selectedPerson.currency)],['Payment structure',label(selectedPerson.payment_structure)],['Notes',selectedPerson.notes||'No notes']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>{finance&&<button className="secondary" onClick={()=>{setPersonForm(selectedPerson);setSelectedPerson(null)}}>Edit personnel</button>}{finance&&<PaymentDetails key={selectedPerson.id} personId={selectedPerson.id}/>}</TabsContent><TabsContent value="work records">{recordTable(data.records.filter(r=>r.personnel_id===selectedPerson.id))}</TabsContent><TabsContent value="payments">{finance?data.payments.filter(p=>data.records.find(r=>r.id===p.record_id)?.personnel_id===selectedPerson.id).map(p=><button className="history-item" key={p.id} onClick={()=>openRecord(p.record_id)}><span>{dateLabel(p.payment_date)} / {p.reference}</span><span>{money(p.amount,data.records.find(r=>r.id===p.record_id)!.currency)} / {p.reversed_at?'Reversed':'Recorded'}</span></button>):<p className="muted">Finance access required.</p>}</TabsContent><TabsContent value="documents"><DocumentsTable documents={data.documents.filter(d=>data.records.find(r=>r.id===d.record_id)?.personnel_id===selectedPerson.id)}/></TabsContent><TabsContent value="activity"><Timeline activity={data.activity.filter(a=>a.object_id===selectedPerson.id||data.records.some(r=>r.personnel_id===selectedPerson.id&&r.id===a.record_id))}/></TabsContent></Tabs></SheetContent></Sheet>}
 {directory&&<Modal title={(directory.id?'Edit ':'Add ')+directory.kind} description="Changes are recorded in the audit trail." onClose={()=>!saving&&setDirectory(null)}><form onSubmit={saveDirectory}><Field label="Name"><input required maxLength={150} value={directory.name} onChange={e=>setDirectory({...directory,name:e.target.value})}/></Field>{directory.kind==='department'&&<Field label="Receipt department code"><input required pattern="[A-Z]{2}" maxLength={2} placeholder="GD" value={directory.code||''} onChange={e=>setDirectory({...directory,code:e.target.value.toUpperCase()})}/><small>Two letters. Example receipt: ASGD-260916-001.</small></Field>}{directory.kind==='project'&&<Field label="Status"><Choice value={directory.status} onChange={v=>setDirectory({...directory,status:v})} options={['active','archived']}/></Field>}{formError&&<p className="error">{formError}</p>}<div className="form-footer"><button className="primary" disabled={saving}>{saving?<Busy/>:'Save'}</button></div></form></Modal>}
 {profileForm&&<Modal title="Workspace access" description="Use the UUID of an account created in Supabase Auth. Authorizing a profile does not send an invitation." onClose={()=>!saving&&setProfileForm(null)}><form onSubmit={saveProfile}><Field label="Auth user ID"><input required disabled={data?.profiles.some(p=>p.id===profileForm.id)} value={profileForm.id} onChange={e=>setProfileForm({...profileForm,id:e.target.value})}/></Field><Field label="Full name"><input required value={profileForm.full_name} onChange={e=>setProfileForm({...profileForm,full_name:e.target.value})}/></Field><Field label="Role"><Choice value={profileForm.role} onChange={v=>setProfileForm({...profileForm,role:v})} options={['super_admin','finance','manager','viewer','employee']}/></Field><Field label="Access"><Choice value={profileForm.active?'active':'inactive'} onChange={v=>setProfileForm({...profileForm,active:v==='active'})} options={['active','inactive']}/></Field>{formError&&<p className="error">{formError}</p>}<div className="form-footer"><button className="primary" disabled={saving}>{saving?<Busy/>:'Save access'}</button></div></form></Modal>}
 <CommandDialog open={command} onOpenChange={setCommand} title="Search workspace" description="Find personnel, statements, receipts, projects and transaction references."><CommandInput placeholder="Search ID, name, statement, receipt or transaction…"/><CommandList><CommandEmpty>No matching records found.</CommandEmpty><CommandGroup heading="Navigate">{navigation.map(([name,Icon])=><CommandItem key={name} onSelect={()=>{navigate(name);setCommand(false)}}><Icon size={15}/>{name}</CommandItem>)}</CommandGroup>{data&&<><CommandGroup heading="Personnel">{data.personnel.map(p=><CommandItem key={p.id} value={p.personnel_code+' '+p.legal_name} onSelect={()=>{setSelectedPerson(p);setCommand(false)}}>{p.personnel_code} / {p.legal_name}</CommandItem>)}</CommandGroup><CommandGroup heading="Statements">{data.records.map(r=><CommandItem key={r.id} value={r.statement_number+' '+personFor(r)?.legal_name+' '+personFor(r)?.personnel_code} onSelect={()=>openRecord(r.id)}>{r.statement_number} / {personFor(r)?.legal_name}</CommandItem>)}</CommandGroup><CommandGroup heading="Payments">{data.payments.map(p=><CommandItem key={p.id} value={p.reference+' '+p.receipt_number} onSelect={()=>openRecord(p.record_id)}>{p.reference} / {p.receipt_number}</CommandItem>)}</CommandGroup><CommandGroup heading="Projects">{data.projects.map(p=><CommandItem key={p.id} value={p.name} onSelect={()=>{navigate('Projects');setCommand(false)}}>{p.name}</CommandItem>)}</CommandGroup></>}</CommandList></CommandDialog>
 </SidebarProvider>
}

