import {z} from 'zod';
import {currencies} from './money';
const uuid=z.string().uuid(),short=z.string().trim().max(200),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const onboardSchema=z.object({request_id:uuid,given_name:short.min(1),family_name:short.min(1),legal_name:short.min(1),display_name:short,email:z.string().toLowerCase().regex(/^[a-z0-9]+([._-][a-z0-9]+)*@aerinyustudios\.com$/,'Use a valid aerinyustudios.com email.'),engagement:z.enum(['employee','contractor','freelancer','other']),department_id:uuid,manager_id:uuid.nullable(),position:short.min(1),team:short,start_date:date,currency:z.enum(currencies),personal_email:z.union([z.literal(''),z.string().email().max(200)]),phone:z.string().max(80),date_of_birth:z.union([z.literal(''),date]),residential_address:z.string().max(1000),country_of_residence:short});
export const employmentSchema=z.object({id:uuid,expected_version:z.number().int().positive(),legal_name:short.min(1),display_name:short,engagement:z.enum(['employee','contractor','freelancer','other']),department_id:uuid,manager_id:uuid.nullable(),position:short.min(1),team:short,status:z.enum(['active','inactive','suspended','departed']),end_date:z.union([z.literal(''),date])});
const personal=z.object({personal_email:z.union([z.literal(''),z.string().email().max(200)]),phone:z.string().max(80),date_of_birth:z.union([z.literal(''),date]),residential_address:z.string().max(1000),country_of_residence:short});
const payment=z.object({payment_method:z.enum(['bank_transfer','cash','wallet','other']),currency:z.enum(currencies),bank_name:short,account_holder:short,account_number:z.string().max(100)});
export const changeSchema=z.discriminatedUnion('kind',[z.object({personnel_id:uuid,kind:z.literal('personal'),payload:personal}),z.object({personnel_id:uuid,kind:z.literal('payment'),payload:payment})]);
export const peopleActions={employment:{schema:employmentSchema,rpc:'update_employee'},head:{schema:z.object({id:uuid,head_id:uuid.nullable()}),rpc:'set_department_head'},checklist:{schema:z.object({id:uuid,done:z.boolean()}),rpc:'set_employee_checklist'},change:{schema:changeSchema,rpc:'request_employee_change'},review:{schema:z.object({id:uuid,decision:z.enum(['approved','rejected'])}),rpc:'review_employee_change'}};
