import {createClient,SupabaseClient} from '@supabase/supabase-js';
import {NextRequest,NextResponse} from 'next/server';
import {z} from 'zod';
import {isWorkspaceIdentity,hasOAuthAuthentication} from './workspace-auth';
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export function configured(){return Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_ANON_KEY)}
export function client(token?:string){if(!configured())throw new ApiError(503,'Workspace setup is incomplete. Configure Supabase before continuing.');return createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:token?{headers:{Authorization:`Bearer ${token}`}}:undefined});}
export function checkOrigin(req:NextRequest){const origin=req.headers.get('origin');if(!origin||origin!==req.nextUrl.origin)throw new ApiError(403,'This request must come from the workspace.');}
export async function readLimited(req:NextRequest,limit:number){if(Number(req.headers.get('content-length')||0)>limit)throw new ApiError(413,'Request is too large.');const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();throw new ApiError(413,'Request is too large.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;}
export async function body(req:NextRequest){const text=new TextDecoder().decode(await readLimited(req,150000));try{return JSON.parse(text)}catch{throw new ApiError(400,'Invalid request.')}}
export function secure(req:NextRequest){return req.nextUrl.protocol==='https:'}
export function sessionCookies(res:NextResponse,req:NextRequest,session:{access_token:string;refresh_token:string;expires_in:number}){const options={httpOnly:true,secure:secure(req),sameSite:'strict' as const,path:'/'};res.cookies.set('as_access',session.access_token,{...options,maxAge:session.expires_in});res.cookies.set('as_refresh',session.refresh_token,{...options,maxAge:60*60*24*7});}
export async function withAuth(req:NextRequest,fn:(db:SupabaseClient,user:{id:string},profile:any)=>Promise<NextResponse>){let refreshed:any=null;try{if(req.method!=='GET')checkOrigin(req);let token=req.cookies.get('as_access')?.value;let db=client(token);let {data:{user}}=await db.auth.getUser(token);if(!user){const refresh=req.cookies.get('as_refresh')?.value;if(!refresh)throw new ApiError(401,'Sign in to continue.');const result=await client().auth.refreshSession({refresh_token:refresh});if(result.error||!result.data.session)throw new ApiError(401,'Your session expired. Sign in again.');refreshed=result.data.session;token=refreshed.access_token;db=client(token);user=result.data.user;}if(!user)throw new ApiError(401,'Sign in to continue.');if(!isWorkspaceIdentity(user)||!token||!hasOAuthAuthentication(token))throw new ApiError(401,'Sign in with your company Google Workspace account.');const {data:profile,error}=await db.from('profiles').select('id,full_name,role,active').eq('id',user.id).single();if(error||!profile?.active)throw new ApiError(403,'Your account has not been authorized for this workspace.');const res=await fn(db,user,profile);res.headers.set('Cache-Control','private, no-store');if(refreshed)sessionCookies(res,req,refreshed);return res;}catch(e){const res=failure(e);if(refreshed)sessionCookies(res,req,refreshed);return res;}}
export function failure(e:unknown){if(e instanceof z.ZodError)return NextResponse.json({error:e.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')},{status:400,headers:{'Cache-Control':'no-store'}});const status=e instanceof ApiError?e.status:500;if(status===500)console.error('Workspace operation failed:',e instanceof Error?e.message:'Unknown error');return NextResponse.json({error:e instanceof ApiError?e.message:'The operation could not be completed. Please try again.'},{status,headers:{'Cache-Control':'no-store'}})}
export async function rpc(db:SupabaseClient,name:string,args:Record<string,unknown>={}){const {data,error}=await db.rpc(name,args);if(error){const status=error.code==='42501'?403:error.code==='23505'||error.code==='40001'?409:400;throw new ApiError(status,error.code==='23505'?'This record already exists. Open the existing record to continue.':error.message)}return data;}
export function finance(profile:any){if(!['super_admin','finance'].includes(profile.role))throw new ApiError(403,'Finance access is required.');}
